In [2]:
import numpy as np

In [12]:
a_list = [1,2,3,4,5,6,7,8,9,10]

In [14]:
a_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
a_ = np.array(a_list)

In [18]:
a_

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
#获取维度信息
#计算有几条索引轴
dim = a_.ndim
dim

1

In [30]:
#获取形状 轴上的元素个数
#表示有10个分量,不是集合意义上的大小
shape = a_.shape
shape

(10,)

In [32]:
#访问数组的第一个元素
a_[0]

1

In [34]:
a_[1]

2

In [36]:
a_[-2]

9

In [38]:
#切片
a_[0:2]

array([1, 2])

In [40]:
a_[:2]

array([1, 2])

In [42]:
a_[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
a_[-3:]

array([ 8,  9, 10])

In [48]:
a_[7:]

array([ 8,  9, 10])

In [51]:
#二维数组创建向

In [53]:
import numpy as np

In [57]:
row_vector = np.array([[1,2,3,4,5,6,7,8,9,10]])
print('row_vector = ',row_vector)

row_vector =  [[ 1  2  3  4  5  6  7  8  9 10]]


In [61]:
print('row_vector.ndim = ',row_vector.ndim)

row_vector.ndim =  2


In [65]:
print('row_vector.shape = ',row_vector.shape)

row_vector.shape =  (1, 10)


In [67]:
#索引操作

In [69]:
print('row_vector[0,0] = ',row_vector[0,0])

row_vector[0,0] =  1


In [71]:
print('row_vector[0,1] = ',row_vector[0,1])

row_vector[0,1] =  2


In [73]:
print('row_vector[0,-1] = ',row_vector[0,-1])

row_vector[0,-1] =  10


In [75]:
#切片操作

In [79]:
print('row_vector[:,:2] = ',row_vector[:,:2])

row_vector[:,:2] =  [[1 2]]


In [81]:
row_vector[:,:2]

array([[1, 2]])

In [85]:
print('row_vector[:,1:] = ',row_vector[:,1:])

row_vector[:,1:] =  [[ 2  3  4  5  6  7  8  9 10]]


In [91]:
print('row_vector[:,-3:] = ',row_vector[:,-3:])

row_vector[:,-3:] =  [[ 8  9 10]]


In [93]:
#二维列向量

In [95]:
col_vector = row_vector.T

In [97]:
print('col_vector = ',col_vector)

col_vector =  [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [99]:
#列向量索引操作

In [101]:
print('col_vector[0,0] = ',col_vector[0,0])

col_vector[0,0] =  1


In [103]:
print('col_vector[1,0] = ',col_vector[1,0])

col_vector[1,0] =  2


In [107]:
print('col_vector[-1,0] = ',col_vector[-1,0])

col_vector[-1,0] =  10


In [109]:
#列向量切片操作

In [115]:
print('col_vector[:2,:] = ',col_vector[:2,:])

col_vector[:2,:] =  [[1]
 [2]]


In [117]:
print('col_vector[1:,:] = ',col_vector[1:,:])

col_vector[1:,:] =  [[ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [123]:
print('col_vector[-3:,:] = ',col_vector[-3:,:])

col_vector[-3:,:] =  [[ 8]
 [ 9]
 [10]]


In [127]:
import matplotlib.pyplot as plt

In [132]:
plt.tight_layout()#紧凑布局
#只关心当前call中的参数fig,而不是之前上下文的call中的fig,因为这里没有fig,无法显示
plt.show() #显示所有图形

<Figure size 640x480 with 0 Axes>

坐标系

In [140]:
import numpy as np
#范围-4,4 步长为1
x1 = np.arange(-4,5,1)
x2 = np.arange(-4,5,1)

xx1,xx2 = np.meshgrid(x1,x2)

In [142]:
#创建二维网格数

In [144]:
import numpy as np

In [146]:
x1 = np.arange(-4,5,1)
x2 = np.arange(-4,5,1)

In [148]:
xx1,xx2 = np.meshgrid(x1,x2)

In [150]:
xx1

array([[-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [152]:
xx2

array([[-4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4]])

In [154]:
xx1.shape

(9, 9)

In [156]:
xx1.ndim

2

In [158]:
xx2.shape

(9, 9)

In [160]:
xx2.ndim

2

In [162]:
#创建三维网格数据

In [164]:
import numpy as np

In [166]:
x1 = np.arange(-4,5,1)
x2 = x1
x3 = x1

In [170]:
xxx1,xxx2,xxx3 = np.meshgrid(x1,x2,x3)

In [172]:
xxx1

array([[[-4, -4, -4, -4, -4, -4, -4, -4, -4],
        [-3, -3, -3, -3, -3, -3, -3, -3, -3],
        [-2, -2, -2, -2, -2, -2, -2, -2, -2],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4]],

       [[-4, -4, -4, -4, -4, -4, -4, -4, -4],
        [-3, -3, -3, -3, -3, -3, -3, -3, -3],
        [-2, -2, -2, -2, -2, -2, -2, -2, -2],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4]],

       [[-4, -4, -4, -4, -4, -4, -4, -4, -4],
        [-3, -3, -3, -3, -3, -3, -3, -3, -3],
        [-2, -2, -2, -2, -2, -2, -2, -2, -2],
        [-1, -1, -1, -1, -1, -

In [174]:
xxx2

array([[[-4, -4, -4, -4, -4, -4, -4, -4, -4],
        [-4, -4, -4, -4, -4, -4, -4, -4, -4],
        [-4, -4, -4, -4, -4, -4, -4, -4, -4],
        [-4, -4, -4, -4, -4, -4, -4, -4, -4],
        [-4, -4, -4, -4, -4, -4, -4, -4, -4],
        [-4, -4, -4, -4, -4, -4, -4, -4, -4],
        [-4, -4, -4, -4, -4, -4, -4, -4, -4],
        [-4, -4, -4, -4, -4, -4, -4, -4, -4],
        [-4, -4, -4, -4, -4, -4, -4, -4, -4]],

       [[-3, -3, -3, -3, -3, -3, -3, -3, -3],
        [-3, -3, -3, -3, -3, -3, -3, -3, -3],
        [-3, -3, -3, -3, -3, -3, -3, -3, -3],
        [-3, -3, -3, -3, -3, -3, -3, -3, -3],
        [-3, -3, -3, -3, -3, -3, -3, -3, -3],
        [-3, -3, -3, -3, -3, -3, -3, -3, -3],
        [-3, -3, -3, -3, -3, -3, -3, -3, -3],
        [-3, -3, -3, -3, -3, -3, -3, -3, -3],
        [-3, -3, -3, -3, -3, -3, -3, -3, -3]],

       [[-2, -2, -2, -2, -2, -2, -2, -2, -2],
        [-2, -2, -2, -2, -2, -2, -2, -2, -2],
        [-2, -2, -2, -2, -2, -2, -2, -2, -2],
        [-2, -2, -2, -2, -2, -

In [176]:
xxx3

array([[[-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4]],

       [[-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4]],

       [[-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-4, -3, -2, -1,  0,  

In [178]:
xxx1.shape

(9, 9, 9)

In [180]:
xxx1.ndim

3

In [182]:
import numpy as np

In [184]:
a = np.array([3,4])
a

array([3, 4])

In [188]:
b = np.array([1,2,2])
b

array([1, 2, 2])

In [190]:
#计算长度

In [192]:
length_a = np.linalg.norm(a)
length_a

5.0

In [198]:
np.sqrt(a[0]**2 + a[1]**2)

5.0

In [194]:
length_b = np.linalg.norm(b)
length_b

3.0

In [196]:
np.sqrt(b[0]**2 + b[1]**2 + b[2]**2 )

3.0