In [3]:
#q1

In [5]:
import numpy as np

In [11]:
q1_a1 = np.array([1,0])
q1_a2 = np.array([0,1])

q1_a1_norm = np.linalg.norm(q1_a1)
q1_a2_norm = np.linalg.norm(q1_a2)

In [17]:
q1_a_dot = np.dot(q1_a1,q1_a2)
q1_costheta = q1_a_dot / (q1_a1_norm*q1_a2_norm)
q1_theta = np.arccos(q1_costheta)
q1_theta_deg = np.rad2deg(q1_theta)
print(q1_a_dot)
print(q1_theta_deg)

0
90.0


In [21]:
q1_array = np.array([[[1,0],[0,1]],[[-1,0],[0,-1]],[[1,0],[-1,0]],[[3,4],[-4,3]]])

In [49]:
for array in q1_array:
    a1 = array[0]
    a2 = array[1]
    print('a1: %r , a2 : %r'  %(a1,a2))
    a1_norm = np.linalg.norm(a1)
    a2_norm = np.linalg.norm(a2)
    a_dot = np.dot(a1,a2)
    a_costheta = a_dot / (a1_norm*a2_norm)
    a_theta = np.arccos(a_costheta)
    a_theta_deg = np.rad2deg(a_theta)
    print('dot: %r , theta: %r'  %(a_dot,a_theta_deg))

a1: array([1, 0]) , a2 : array([0, 1])
dot: 0 , theta: 90.0
a1: array([-1,  0]) , a2 : array([ 0, -1])
dot: 0 , theta: 90.0
a1: array([1, 0]) , a2 : array([-1,  0])
dot: -1 , theta: 180.0
a1: array([3, 4]) , a2 : array([-4,  3])
dot: 0 , theta: 90.0


In [55]:
#q4

In [123]:
e1 = np.array([1,0,0])
e2 = np.array([0,1,0])
e3 = np.array([0,0,1])
e1_2 = e1+e2
e1_3 = e1+e3
e2_3 = e2+e3
e1_2_3 = e1+e2+e3

e_every = [e1,e2,e3,e1_2,e1_3,e2_3,e1_2_3]
e_every

[array([1, 0, 0]),
 array([0, 1, 0]),
 array([0, 0, 1]),
 array([1, 1, 0]),
 array([1, 0, 1]),
 array([0, 1, 1]),
 array([1, 1, 1])]

In [131]:
i = 1
for e_vec in e_every:
    if i <= 6:
        #这里的切片是一位数组的,举例二维数组切片(与本题目无关)[i::,i::]是有','的
        for e_vec2 in e_every[i::]:

            e_vec_norm = np.linalg.norm(e_vec)
            e_vec2_norm = np.linalg.norm(e_vec2)
            
            e_dot = np.dot(e_vec,e_vec2)
            e_costheta = e_dot / (e_vec_norm*e_vec2_norm)
            e_theta_rad = np.arccos(e_costheta)
            e_theta_deg = np.rad2deg(e_theta_rad)
    
            print('current two vectors:  %r  ,  %r' %(e_vec,e_vec2))
            print('two vectors dot: %r' %e_dot)
            print('two vectors cos: %.2f' %e_costheta)
            print('two vectors theta_deg: %.2f' %e_theta_deg)
    
            print('\n')

        i = i+1

current two vectors:  array([1, 0, 0])  ,  array([0, 1, 0])
two vectors dot: 0
two vectors cos: 0.00
two vectors theta_deg: 90.00


current two vectors:  array([1, 0, 0])  ,  array([0, 0, 1])
two vectors dot: 0
two vectors cos: 0.00
two vectors theta_deg: 90.00


current two vectors:  array([1, 0, 0])  ,  array([1, 1, 0])
two vectors dot: 1
two vectors cos: 0.71
two vectors theta_deg: 45.00


current two vectors:  array([1, 0, 0])  ,  array([1, 0, 1])
two vectors dot: 1
two vectors cos: 0.71
two vectors theta_deg: 45.00


current two vectors:  array([1, 0, 0])  ,  array([0, 1, 1])
two vectors dot: 0
two vectors cos: 0.00
two vectors theta_deg: 90.00


current two vectors:  array([1, 0, 0])  ,  array([1, 1, 1])
two vectors dot: 1
two vectors cos: 0.58
two vectors theta_deg: 54.74


current two vectors:  array([0, 1, 0])  ,  array([0, 0, 1])
two vectors dot: 0
two vectors cos: 0.00
two vectors theta_deg: 90.00


current two vectors:  array([0, 1, 0])  ,  array([1, 1, 0])
two vectors dot:

In [277]:
#q5
np.random.randint(10) #10以下不包含10的整数随机数

vec_ran1 = np.array([])
vec_ran2 = np.array([])

#for 可以改成 for _ range(3):      但是每次append开销很大
#使用函数可直接生成随机数   vec_ran1 = np.random.randint(0,10,size = 3)
for a in [1,1,1]:
    randint = np.random.randint(10)
    vec_ran1 = np.append(vec_ran1,randint)
for a in [1,1,1]:
    randint = np.random.randint(10)
    vec_ran2 = np.append(vec_ran2,randint)

vec_ran1_norm = np.linalg.norm(vec_ran1)
vec_ran2_norm = np.linalg.norm(vec_ran2)

dot = np.dot(vec_ran1,vec_ran2)
costheta = dot / (vec_ran1_norm*vec_ran2_norm)
theta_rad = np.arccos(costheta)
theta_deg = np.rad2deg(theta_rad)

print('dot:',dot)
print('theta_deg:',theta_deg)

dot: 50.0
theta_deg: 34.03028012065824
