In [1]:
#q1

In [3]:
import numpy as np

In [13]:
q1_arr = np.eye(3)

In [19]:
q1_a = q1_arr[:,0]
q1_b = q1_arr[:,1]
q1_c = q1_arr[:,2]

In [21]:
np.dot(q1_a,q1_b)

0.0

In [23]:
np.dot(q1_a,q1_c)

0.0

In [25]:
np.dot(q1_b,q1_c)

0.0

In [27]:
#q2

In [37]:
q2_arr1 = np.random.randint(1,10,(5,5))
q2_arr1

array([[8, 7, 7, 3, 4],
       [9, 7, 8, 1, 4],
       [3, 4, 6, 8, 4],
       [2, 2, 6, 7, 3],
       [4, 8, 3, 6, 6]])

In [39]:
q2_arr2 = np.random.randint(1,10,(5,10))
q2_arr2

array([[9, 7, 4, 6, 8, 7, 4, 9, 5, 4],
       [9, 2, 9, 1, 8, 2, 7, 2, 3, 1],
       [4, 9, 4, 3, 7, 2, 3, 1, 4, 9],
       [4, 7, 3, 7, 1, 6, 7, 9, 6, 2],
       [6, 8, 4, 2, 1, 5, 3, 3, 2, 1]])

In [43]:
q2_arr3 = np.random.randint(1,10,(10,5))
q2_arr3

array([[8, 4, 4, 3, 8],
       [4, 7, 2, 3, 9],
       [5, 9, 8, 4, 6],
       [7, 1, 7, 4, 3],
       [6, 3, 5, 5, 9],
       [3, 3, 4, 2, 1],
       [3, 5, 3, 7, 2],
       [6, 2, 2, 1, 4],
       [9, 3, 5, 4, 1],
       [9, 8, 3, 4, 2]])

In [94]:
def diagonal(array):
    q2_diag_1d = np.array([])
    if array.shape[0] >= array.shape[1]:
        for i in np.arange(0,array.shape[1]):
            q2_diag_1d = np.append(q2_diag_1d,array[i,i])
        print(q2_diag_1d)

    elif array.shape[0] < array.shape[1]:
        for i in np.arange(0,array.shape[0]):
            q2_diag_1d = np.append(q2_diag_1d,array[i,i])  
        print(q2_diag_1d)

    return q2_diag_1d


In [96]:
diagonal(q2_arr1)

[8. 7. 6. 7. 6.]


array([8., 7., 6., 7., 6.])

In [98]:
diagonal(q2_arr2)

[9. 2. 4. 7. 1.]


array([9., 2., 4., 7., 1.])

In [100]:
diagonal(q2_arr3)

[8. 7. 8. 4. 9.]


array([8., 7., 8., 4., 9.])

In [102]:
#q3

In [104]:
q3_arr1 = diagonal(q2_arr1)
q3_arr2 = diagonal(q2_arr2)
q3_arr3 = diagonal(q2_arr3)

[8. 7. 6. 7. 6.]
[9. 2. 4. 7. 1.]
[8. 7. 8. 4. 9.]


In [106]:
def build_diagonal(array_1d):
    for i in np.arange(0,array_1d.shape):
        

array([8., 7., 6., 7., 6.])