In [1]:
import numpy as np

In [3]:
a = np.array([[1],
             [2],
             [3]])

In [5]:
a_1D = np.array([1,2,3])

In [6]:
b = np.array([[-4],
              [-5],
              [-6]])

In [7]:
b_1D = np.array([-4,-5,-6])

In [8]:
np.einsum('ij->',a)

np.int64(6)

In [9]:
np.einsum('i->',a_1D)

np.int64(6)

In [10]:
np.einsum('ij,ij -> ij',a,b)

array([[ -4],
       [-10],
       [-18]])

In [11]:
np.einsum('i,i->i',a_1D,b_1D)

array([ -4, -10, -18])

In [12]:
np.einsum('ij,ij->',a,b)

np.int64(-32)

In [13]:
np.einsum('i,i->',a_1D,b_1D)

np.int64(-32)

In [16]:
np.einsum('ij,ji->ij',a,a) #ij表示轴的维度,而不是轴的元素个数

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [17]:
np.einsum('i,j->ij',a_1D,a_1D)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [18]:
np.einsum('ij,ji->ij',a,b)

array([[ -4,  -5,  -6],
       [ -8, -10, -12],
       [-12, -15, -18]])

In [19]:
np.einsum('i,j->ij',a_1D,b_1D)

array([[ -4,  -5,  -6],
       [ -8, -10, -12],
       [-12, -15, -18]])

In [20]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
B = np.array([[-1,-4,-7],
              [-2,-5,-8],
              [-3,-6,-9]])

In [21]:
np.einsum('ji',A)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [23]:
np.einsum('ij->',A)

np.int64(45)

In [24]:
np.einsum('ij->j',A)

array([12, 15, 18])

In [25]:
np.einsum('ij->i',A)

array([ 6, 15, 24])

In [26]:
np.einsum('ii->',A)

np.int64(15)

In [27]:
np.einsum('ij,jk->ik',A,B)

array([[ -14,  -32,  -50],
       [ -32,  -77, -122],
       [ -50, -122, -194]])

In [28]:
np.einsum('ij,jk->',A,B)

np.int64(-693)

In [29]:
np.einsum('ij,jk->ki',A,B)

array([[ -14,  -32,  -50],
       [ -32,  -77, -122],
       [ -50, -122, -194]])

In [30]:
np.einsum('ij,ij->ij',A,B)

array([[ -1,  -8, -21],
       [ -8, -25, -48],
       [-21, -48, -81]])