In [1]:
import numpy as np

In [2]:
A = np.matrix([[1.25,-0.75],
               [-0.75,1.25]])

In [3]:
Lambda,V = np.linalg.eig(A)
Lambda

array([2. , 0.5])

In [4]:
V

matrix([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]])

In [5]:
B = V @ np.diag(np.sqrt(Lambda)) @ np.linalg.inv(V)

In [7]:
B

matrix([[ 1.06066017, -0.35355339],
        [-0.35355339,  1.06066017]])

In [8]:
A_reproduced = B @ B
A_reproduced

matrix([[ 1.25, -0.75],
        [-0.75,  1.25]])