In [63]:
import numpy as np

In [17]:
#Q1

In [19]:
a=np.arange(1,6+1)
a

array([1, 2, 3, 4, 5, 6])

In [21]:
b=a.reshape((2,3))

In [23]:
a[0]=100

In [25]:
b

array([[100,   2,   3],
       [  4,   5,   6]])

In [27]:
#Q2

In [31]:
arr=np.arange(1,6+1)

In [39]:
arr_3_by_2=arr.reshape(3,2)
arr_3_by_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
arr_3_by_2.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [45]:
#Q3

In [47]:
arr=np.arange(1,8+1)

In [55]:
arr_4_by_2=arr.reshape((1,4,2))
arr_4_by_2

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [59]:
arr_4_by_2.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
#Q4  使用numpy中的random函数

In [67]:
arr_10_1=np.random.rand(10)
arr_10_2=np.random.rand(10)

In [70]:
row_stack = np.stack((arr_10_1,arr_10_2))
row_stack

array([[0.08765052, 0.04876837, 0.47663472, 0.83527226, 0.36126773,
        0.07516272, 0.12700975, 0.62496965, 0.42942503, 0.74576329],
       [0.8295285 , 0.8170292 , 0.86095706, 0.75692318, 0.6272481 ,
        0.48540929, 0.98947415, 0.79907683, 0.02573753, 0.2152575 ]])

In [74]:
col_stack = np.stack((arr_10_1,arr_10_2),axis=1)
col_stack

array([[0.08765052, 0.8295285 ],
       [0.04876837, 0.8170292 ],
       [0.47663472, 0.86095706],
       [0.83527226, 0.75692318],
       [0.36126773, 0.6272481 ],
       [0.07516272, 0.48540929],
       [0.12700975, 0.98947415],
       [0.62496965, 0.79907683],
       [0.42942503, 0.02573753],
       [0.74576329, 0.2152575 ]])

In [80]:
arr_144=np.random.rand(144)
arr_144

array([0.82590228, 0.47328993, 0.6715262 , 0.50995723, 0.69285789,
       0.23632587, 0.63489261, 0.86908324, 0.93459463, 0.04912469,
       0.13531157, 0.71127348, 0.67747347, 0.41305301, 0.6355454 ,
       0.46858634, 0.10214633, 0.93642513, 0.69141931, 0.84634008,
       0.15363982, 0.44623866, 0.71288324, 0.56808189, 0.92202405,
       0.12804817, 0.55133044, 0.49923115, 0.51461686, 0.32548964,
       0.59386212, 0.54806224, 0.08883728, 0.9888929 , 0.39499589,
       0.06160513, 0.03484833, 0.80904865, 0.82095545, 0.67912344,
       0.48726181, 0.22255299, 0.83612024, 0.46380949, 0.23780496,
       0.94001285, 0.38248811, 0.6489573 , 0.16008254, 0.4096285 ,
       0.61214095, 0.50677794, 0.41726851, 0.09903613, 0.38196082,
       0.43357147, 0.49139426, 0.2271192 , 0.11962731, 0.5004017 ,
       0.46508804, 0.7456278 , 0.19553539, 0.62824824, 0.12505389,
       0.32366991, 0.29710829, 0.91585617, 0.93249083, 0.80125037,
       0.71028709, 0.49420038, 0.06074184, 0.42054236, 0.56039

In [94]:
arr_144=arr_144.reshape((12,12))

In [96]:
np.split(arr_144,3,axis=0)

[array([[0.82590228, 0.47328993, 0.6715262 , 0.50995723, 0.69285789,
         0.23632587, 0.63489261, 0.86908324, 0.93459463, 0.04912469,
         0.13531157, 0.71127348],
        [0.67747347, 0.41305301, 0.6355454 , 0.46858634, 0.10214633,
         0.93642513, 0.69141931, 0.84634008, 0.15363982, 0.44623866,
         0.71288324, 0.56808189],
        [0.92202405, 0.12804817, 0.55133044, 0.49923115, 0.51461686,
         0.32548964, 0.59386212, 0.54806224, 0.08883728, 0.9888929 ,
         0.39499589, 0.06160513],
        [0.03484833, 0.80904865, 0.82095545, 0.67912344, 0.48726181,
         0.22255299, 0.83612024, 0.46380949, 0.23780496, 0.94001285,
         0.38248811, 0.6489573 ]]),
 array([[0.16008254, 0.4096285 , 0.61214095, 0.50677794, 0.41726851,
         0.09903613, 0.38196082, 0.43357147, 0.49139426, 0.2271192 ,
         0.11962731, 0.5004017 ],
        [0.46508804, 0.7456278 , 0.19553539, 0.62824824, 0.12505389,
         0.32366991, 0.29710829, 0.91585617, 0.93249083, 0.80125037,


In [98]:
np.split(arr_144,4,axis=1)

[array([[0.82590228, 0.47328993, 0.6715262 ],
        [0.67747347, 0.41305301, 0.6355454 ],
        [0.92202405, 0.12804817, 0.55133044],
        [0.03484833, 0.80904865, 0.82095545],
        [0.16008254, 0.4096285 , 0.61214095],
        [0.46508804, 0.7456278 , 0.19553539],
        [0.06074184, 0.42054236, 0.56039654],
        [0.18542503, 0.73824417, 0.08414168],
        [0.99945822, 0.80168021, 0.38590291],
        [0.73188905, 0.76574644, 0.26056679],
        [0.03835572, 0.12830301, 0.13805414],
        [0.69767457, 0.88536214, 0.36289067]]),
 array([[0.50995723, 0.69285789, 0.23632587],
        [0.46858634, 0.10214633, 0.93642513],
        [0.49923115, 0.51461686, 0.32548964],
        [0.67912344, 0.48726181, 0.22255299],
        [0.50677794, 0.41726851, 0.09903613],
        [0.62824824, 0.12505389, 0.32366991],
        [0.22658294, 0.85924801, 0.78344731],
        [0.08772793, 0.77266751, 0.6255059 ],
        [0.1220515 , 0.13682536, 0.1028175 ],
        [0.56752986, 0.19064016,

In [100]:
arr_8_by_5=np.random.rand(40).reshape((8,5))
arr_8_by_5

array([[0.48845983, 0.017552  , 0.39754473, 0.18742959, 0.69583878],
       [0.66023082, 0.34804027, 0.48082017, 0.10976558, 0.86208302],
       [0.61071913, 0.29150246, 0.41095078, 0.66759768, 0.09821173],
       [0.49551899, 0.69986337, 0.2637423 , 0.9863469 , 0.19562993],
       [0.77994051, 0.5539594 , 0.61370357, 0.81118421, 0.25910141],
       [0.5642415 , 0.71637641, 0.45307082, 0.05504909, 0.91510283],
       [0.75211201, 0.49424145, 0.51184695, 0.92684094, 0.08473959],
       [0.26835979, 0.36401877, 0.11129592, 0.82508429, 0.77141251]])

In [102]:
arr_3_by_5 = np.random.rand(15).reshape((3,5))
arr_3_by_5

array([[0.2568071 , 0.80213061, 0.43528264, 0.96890829, 0.70901479],
       [0.01568952, 0.73866372, 0.75444656, 0.57539449, 0.09378274],
       [0.96582508, 0.3187614 , 0.80360723, 0.90832093, 0.43779619]])

In [108]:
np.stack((arr_8_by_5,arr_3_by_5),axis=0) #两个数组必须形状相同

ValueError: all input arrays must have the same shape

In [119]:
np.block([[arr_8_by_5],[arr_3_by_5]])

array([[0.48845983, 0.017552  , 0.39754473, 0.18742959, 0.69583878],
       [0.66023082, 0.34804027, 0.48082017, 0.10976558, 0.86208302],
       [0.61071913, 0.29150246, 0.41095078, 0.66759768, 0.09821173],
       [0.49551899, 0.69986337, 0.2637423 , 0.9863469 , 0.19562993],
       [0.77994051, 0.5539594 , 0.61370357, 0.81118421, 0.25910141],
       [0.5642415 , 0.71637641, 0.45307082, 0.05504909, 0.91510283],
       [0.75211201, 0.49424145, 0.51184695, 0.92684094, 0.08473959],
       [0.26835979, 0.36401877, 0.11129592, 0.82508429, 0.77141251],
       [0.2568071 , 0.80213061, 0.43528264, 0.96890829, 0.70901479],
       [0.01568952, 0.73866372, 0.75444656, 0.57539449, 0.09378274],
       [0.96582508, 0.3187614 , 0.80360723, 0.90832093, 0.43779619]])

In [117]:
np.concatenate((arr_8_by_5,arr_3_by_5),axis=0)

array([[0.48845983, 0.017552  , 0.39754473, 0.18742959, 0.69583878],
       [0.66023082, 0.34804027, 0.48082017, 0.10976558, 0.86208302],
       [0.61071913, 0.29150246, 0.41095078, 0.66759768, 0.09821173],
       [0.49551899, 0.69986337, 0.2637423 , 0.9863469 , 0.19562993],
       [0.77994051, 0.5539594 , 0.61370357, 0.81118421, 0.25910141],
       [0.5642415 , 0.71637641, 0.45307082, 0.05504909, 0.91510283],
       [0.75211201, 0.49424145, 0.51184695, 0.92684094, 0.08473959],
       [0.26835979, 0.36401877, 0.11129592, 0.82508429, 0.77141251],
       [0.2568071 , 0.80213061, 0.43528264, 0.96890829, 0.70901479],
       [0.01568952, 0.73866372, 0.75444656, 0.57539449, 0.09378274],
       [0.96582508, 0.3187614 , 0.80360723, 0.90832093, 0.43779619]])