In [1]:
import numpy as np

In [3]:
A = np.array([[1,0.5,1],
              [0.5,2,-0.2],
              [1,-0.2,1]])
A

array([[ 1. ,  0.5,  1. ],
       [ 0.5,  2. , -0.2],
       [ 1. , -0.2,  1. ]])

In [11]:
lambdas,V = np.linalg.eig(A)

In [13]:
lambdas

array([-0.11690876,  2.27277129,  1.84413747])

In [15]:
V

array([[ 0.70427305, -0.54762109,  0.45178602],
       [-0.2298057 , -0.77797224, -0.58476366],
       [-0.67170589, -0.30801028,  0.67375133]])