In [1]:
import numpy as np

In [3]:
def inverse_2x2_A(A):
    """
    A = [[a,b],
         [c,d]]
    """
    a,b = A[0]
    c,d = A[1]

    det = a*d - b*c

    if det == 0:
        print('矩阵不可逆,行列式为0')
        return None

    inv_A = np.array([[d,-b],[c,-a]]) / det
    return inv_A

In [5]:
A = [[1,2],
     [3,4]]
A = np.array(A)
A

array([[1, 2],
       [3, 4]])

In [7]:
inverse_2x2_A(A)

array([[-2. ,  1. ],
       [-1.5,  0.5]])

In [9]:
B = [[0,1],
     [0,2]]
B = np.array(B)
B

array([[0, 1],
       [0, 2]])

In [11]:
inverse_2x2_A(B)

矩阵不可逆,行列式为0


In [14]:
import numpy as np

In [16]:
K = np.array([[1,0.5],
              [0,1]])

In [18]:
K_inv = np.linalg.inv(K)
K_inv

array([[ 1. , -0.5],
       [ 0. ,  1. ]])

In [20]:
K@K_inv

array([[1., 0.],
       [0., 1.]])

In [22]:
K_inv@K

array([[1., 0.],
       [0., 1.]])

In [51]:
import sympy as sp

In [53]:
K = sp.Matrix([[1,0.5],
               [0,1]])
K

Matrix([
[1, 0.5],
[0,   1]])

In [55]:
K_inv = K.inv()
K_inv

Matrix([
[1.0, -0.5],
[  0,  1.0]])

In [57]:
K@K_inv

Matrix([
[1.0,   0],
[  0, 1.0]])

In [59]:
K_inv@K

Matrix([
[1.0,   0],
[  0, 1.0]])

In [81]:
G = sp.Matrix([[0,2],
               [3,0]])
G.inv()

Matrix([
[  0, 1/3],
[1/2,   0]])