In [2]:
import numpy as np

In [10]:
def gauss_elimination(A,b):
    #确保使用浮点数
    A = A.astype(float)
    b = b.astype(float)
    n = len(b)

    #构造增广矩阵
    Ab = np.hstack([A,b.reshape(-1,1)])

    for i in range(n):
        #让每一行的主元变为主对角线元素,每计算到一行主元下边都化为0
        #这个操作确保主元位置不为0,使用绝对值最大的的数值避免很小的数(确保分母不小,确保浮点数误差稳定)
        #argmax返回最大值索引
        #abs取绝对值,其中Ab从左边开始寻找
        max_row = np.argmax(np.abs(Ab[i:,i])) + i #索引是根据Ab的切片来的,加i计算真实行号
        Ab[[i,max_row]] = Ab[[max_row,i]]#交换行,使用的花式索引

        Ab[i] = Ab[i]/Ab[i,i] #主元归一化,作用在整个行

        #消元,用归一化的主元行消去下面所有行中主元下的值,变为0
        for j in range(i+1,n):
            Ab[j] = Ab[j] - Ab[j,i] * Ab[i]

    #带回求解
    x = np.zeros(n) #生成长度为n的数组,而不是矩阵
    for i in range(n-1,-1,-1):
        #切片规则中,如果起点大于等于重点,返回空数组,所以第一次遍历时候i = n-1 这里成了n:n,dot中两个切片都为0
        #切片规则中,a[n:n]中是从n到n(结束时不含n,应为n的上一个),左闭右开,所以是空
        #切片机制中还允许[start,end]的end超过最大合法索引+1,因为左闭右开,右侧实际取值是end - 1是合法的.
            #如果end值比最大合法索引+1还要更多也不会报错,切片值就是到最大合法索引结束
        x[i] = Ab[i,-1] - np.dot(Ab[i,i+1:n],x[i+1:n])

    return x

In [12]:
A = np.array([[1,3,6],
              [2,7,14],
              [0,2,5]])
b = np.array([25,58,19])

In [14]:
x = gauss_elimination(A,b)
x

array([1., 2., 3.])

In [17]:
import numpy as np

In [19]:
def inverse_matrix(A):
    A = np.array(A,dtype = float) #区别于前者,前者仅仅能修改numpyarray,但是这里可以从顶层修改任何数组对象

    #返回元组维度信息,shape()会报错shape不是方法,是其中的信息(成员变量)
    n,m = A.shape

    #判断方阵
    if n != m:
        print('错误,矩阵不是方阵,无法求逆')
        return None

    #计算det判断是否可逆
    if np.linalg.det(A) == 0:
        print('错误,矩阵行列式为0,无法求逆')
        return None

    I = np.eye(n)
    A_I = np.hstack((A,I)) #(A,I)和[A,I]效果一样,只要传入需要拼接的数组即可

    #循环的i变量相当于是列索引
    for i in range(n):
        max_row = np.argmax(np.abs(A_I[i:,i])) +i
        A_I[[i,max_row]] = A_I[[max_row,i]]
        #归一化,让主对角线元素变为1
        A_I[i] = A_I[i] / A_I[i,i]
        
        #消元 使得主元列其他元素变为0
        for j in range(n):
            #确保不修改主元行
            if i != j :
                A_I[j] -= A_I[j,i] * A_I[i]

    A_inv = A_I[:,n:]
    return A_inv

In [21]:
A = np.array([[1,3,6],
              [2,7,14],
              [0,2,5]])

In [23]:
A_inv = inverse_matrix(A)
A_inv

array([[  7.,  -3.,   0.],
       [-10.,   5.,  -2.],
       [  4.,  -2.,   1.]])

In [36]:
b = np.array([[25],
              [58],
              [19]])

In [38]:
A_inv @ b

array([[1.],
       [2.],
       [3.]])

In [40]:
A = np.array([[1,2,3],
              [3,0,1],
              [1,2,1]])

In [42]:
inverse_matrix(A)

array([[-0.16666667,  0.33333333,  0.16666667],
       [-0.16666667, -0.16666667,  0.66666667],
       [ 0.5       , -0.        , -0.5       ]])