In [1]:
import numpy as np

In [3]:
A = np.array([[0,1],
              [1,1],
              [1,0]])

In [5]:
ATA = A.T @ A

In [11]:
eigvals_V,V = np.linalg.eigh(ATA)

In [13]:
eigvals_V

array([1., 3.])

In [15]:
#argsort默认返回升序排序后的索引顺序
#赋值操作复制给本身会覆盖改变原数组,-A只能是生成新数组
idx = np.argsort(-eigvals_V)

eigvals_V = eigvals_V[idx]

V = V[:,idx]

In [19]:
eigvals_V

array([3., 1.])

In [21]:
V

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [23]:
#首先取元素最大值逐个与0比较 防止有0值因为浮点误差产生负值而被开根号,直接比较大小取0值
    #每次从参数1中按照顺序取出一个值与后面的数组比较
    #这里是用到了广播规则,后者0广播变化成了与前者数组相同的结构,按照索引位置依次对比两个数组上的元素大小
        #返回一个同形状数组,记录对比下的最大值
singular_vals = np.sqrt(np.maximum(eigvals_V,0))

In [25]:
singular_vals

array([1.73205081, 1.        ])

In [27]:
#构造S

In [29]:
S = np.zeros_like(A,dtype = float) #dtype的d表示data

In [33]:
#原地填充到主对角线上 参数2的1D数组长度需要≤S的对角线长度
#fill原意为填充,不需要填满,参数2的1D数组长度小于被填充矩阵对角线长度,剩余部分不填
np.fill_diagonal(S,singular_vals)
S

array([[1.73205081, 0.        ],
       [0.        , 1.        ],
       [0.        , 0.        ]])

In [35]:
#计算AAT

In [37]:
AAT = A @ A.T

In [39]:
eigvals_U , U = np.linalg.eigh(AAT)

In [41]:
eigvals_U , U

(array([2.56090598e-16, 1.00000000e+00, 3.00000000e+00]),
 array([[-5.77350269e-01,  7.07106781e-01,  4.08248290e-01],
        [ 5.77350269e-01,  9.13969213e-18,  8.16496581e-01],
        [-5.77350269e-01, -7.07106781e-01,  4.08248290e-01]]))

In [47]:
idx = np.argsort(-eigvals_U)

eigvals_U = eigvals_U[idx]

U = U[:,idx]

In [51]:
idx

array([2, 1, 0])

In [53]:
eigvals_U,U

(array([3.00000000e+00, 1.00000000e+00, 2.56090598e-16]),
 array([[ 4.08248290e-01,  7.07106781e-01, -5.77350269e-01],
        [ 8.16496581e-01,  9.13969213e-18,  5.77350269e-01],
        [ 4.08248290e-01, -7.07106781e-01, -5.77350269e-01]]))

In [55]:
#还原A

In [57]:
A_reconstructed = U@S@V.T
#四舍五入保留5位小数
np.round(A_reconstructed,5)

array([[0., 1.],
       [1., 1.],
       [1., 0.]])

In [59]:
#用numpy

In [61]:
U,S,V = np.linalg.svd(A,full_matrices = True)

In [63]:
U,S,V

(array([[-4.08248290e-01,  7.07106781e-01,  5.77350269e-01],
        [-8.16496581e-01,  7.45552182e-17, -5.77350269e-01],
        [-4.08248290e-01, -7.07106781e-01,  5.77350269e-01]]),
 array([1.73205081, 1.        ]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

In [67]:
S_s = np.zeros_like(A,dtype = float)
np.fill_diagonal(S_s,S)

In [71]:
A_reconstructed_2 = U @ S_s @ V.T
A_reconstructed_2

array([[ 1.02120423e-16,  1.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00, -2.11898069e-16]])