In [1]:
import numpy as np

In [3]:
A = np.array([[1,1],
              [2,4]]) #系数矩阵

In [5]:
b = np.array([[35],
              [94]]) #常数列向量

In [19]:
np.linalg.det(A)#用行列式判断是否可逆

2.0

In [7]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 2. , -0.5],
       [-1. ,  0.5]])

In [9]:
A_inv@A

array([[1., 0.],
       [0., 1.]])

In [11]:
A@A_inv

array([[1., 0.],
       [0., 1.]])

In [15]:
A_inv@b

array([[23.],
       [12.]])

In [21]:
import numpy as np

In [23]:
A = np.array([[1,1],
              [2,4]])

In [25]:
b = np.array([[35],
              [94]])

In [29]:
x = np.linalg.solve(A,b) #lin是linear alg是algebra
x

array([[23.],
       [12.]])

In [31]:
from sympy import Matrix

In [33]:
A = Matrix([[1,1],
            [2,4]])
A

Matrix([
[1, 1],
[2, 4]])

In [35]:
b = Matrix([[35],
            [94]])
b

Matrix([
[35],
[94]])

In [37]:
x = A.LUsolve(b)
x

Matrix([
[23],
[12]])