In [1]:
import numpy as np

In [3]:
A = np.array([[1,2,3],
              [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
B = A.T
B

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
C = A@B
C

array([[14, 32],
       [32, 77]])

In [11]:
A[[0],:]

array([[1, 2, 3]])

In [13]:
B[:,[0]]

array([[1],
       [2],
       [3]])

In [15]:
A[[0],:] @ B[:,[0]]

array([[14]])

In [17]:
rows,cols = C.shape
C_manual = np.zeros((rows,cols))

In [19]:
for i in range(rows):
    for j in range(cols):
        c_ij = A[[i],:] @ B[:,[j]]  #得到1x1的二维矩阵
        c_ij = c_ij[0][0]  #提取二维矩阵中的标量
        C_manual[i,j] = c_ij #将标量赋予给正确位置

In [21]:
C_manual

array([[14., 32.],
       [32., 77.]])

In [23]:
#B@A

In [25]:
B[[0],:]

array([[1, 4]])

In [27]:
A[:,[0]]

array([[1],
       [4]])

In [29]:
B[[0],:] @ A[:,[0]]

array([[17]])

In [33]:
D = B@A
D

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [35]:
rows,cols = D.shape
D_manual = np.zeros((rows,cols))

In [39]:
for i in range(rows):
    for j in range(cols):
        d_ij = B[[i],:] @ A[:,[j]]
        d_ij = d_ij[0][0]
        D_manual[i,j] = d_ij  #D_manual[i,j]中不论在左边赋值还是右边取值,永远代表对应i行j列的那个标量

In [41]:
D_manual

array([[17., 22., 27.],
       [22., 29., 36.],
       [27., 36., 45.]])

In [43]:
#矩阵乘法内积视角

In [45]:
import numpy as np

In [47]:
def matrix_multiplication_inner(A,B):
    m,p_A = A.shape
    p_B,n = B.shape

    if p_A != p_B:
        raise ValueError('Dimensions do not match')

    C = np.zeros((m,n))

    for i in range(m):
        for j in range(n):
            row_i_A = A[i,:]
            col_j_B = B[:,j]
            C[i,j] = np.dot(row_i_A,col_j_B)
    return C

In [49]:
A = np.array([[1,2,3],
              [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
B = A.T
B

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
matrix_multiplication_inner(A,B)

array([[14., 32.],
       [32., 77.]])

In [55]:
matrix_multiplication_inner(B,A)

array([[17., 22., 27.],
       [22., 29., 36.],
       [27., 36., 45.]])