In [145]:
import numpy as np

In [147]:
def get_minor(matrix,row,col):
    """
    提取余子矩阵,去掉指定的行和列
    """
    return np.delete(np.delete(matrix,row,axis = 0),col,axis = 1)

In [149]:
def determinant(matrix):
    """
    递归计算行列式 (Laplace 展开)
    """
    n = matrix.shape[0]
    if n == 1:
        return matrix[0,0]
    if n ==2:
        return matrix[0,0]*matrix[1,1] - matrix[0,1]*matrix[1,0]

    det = 0
    for col in range(n):
        minor = get_minor(matrix,0,col)
        cofactor = ((-1) ** col) * determinant(minor)
        det += matrix[0,col] * cofactor

    return det

In [151]:
def cofactor_matrix(matrix):
    """
    计算代数余子式矩阵
    """
    n = matrix.shape[0]
    cof_matrix = np.zeros((n,n))

    for row in range(n):
        for col in range(n):
            minor = get_minor(matrix,row,col)
            cof_matrix[row,col] = ((-1) ** (row+col)) * determinant(minor)

    return cof_matrix

In [153]:
def adjugate_matrix(matrix):
    """
    计算伴随矩阵,代数余子式矩阵的转置
    """
    return cofactor_matrix(matrix).T

In [155]:
def inverse_matrix(matrix):
    """
    计算矩阵的逆矩阵(如果存在)
    """
    det = determinant(matrix)
    if det == 0:
        raise ValueError('矩阵不可逆,行列式为0')

    adj = adjugate_matrix(matrix)
    return adj/det

In [167]:
A = np.array([[1,2,3],
              [3,0,1],
              [1,2,1]])

In [169]:
A_inv = inverse_matrix(A)
A_inv

array([[-0.16666667,  0.33333333,  0.16666667],
       [-0.16666667, -0.16666667,  0.66666667],
       [ 0.5       ,  0.        , -0.5       ]])

In [171]:
get_minor(A,0,0)

array([[0, 1],
       [2, 1]])

In [173]:
determinant(get_minor(A,1,1))

-2

In [175]:
cofactor_matrix(A)

array([[-2., -2.,  6.],
       [ 4., -2.,  0.],
       [ 2.,  8., -6.]])