In [1]:
#Q1 cholesky分解

In [3]:
import numpy as np

In [5]:
A = np.array([[5/4,-3/4],
              [-3/4,5/4]])

In [11]:
R_T = np.linalg.cholesky(A) #默认返回下三角矩阵

In [13]:
R_T

array([[ 1.11803399,  0.        ],
       [-0.67082039,  0.89442719]])

In [15]:
R = R_T.T
R

array([[ 1.11803399, -0.67082039],
       [ 0.        ,  0.89442719]])

In [17]:
#Q2

In [21]:
from scipy.linalg import ldl

In [23]:
lu,d,perm = ldl(A)

In [25]:
lu

array([[ 1. ,  0. ],
       [-0.6,  1. ]])

In [27]:
d

array([[1.25, 0.  ],
       [0.  , 0.8 ]])

In [29]:
perm

array([0, 1])