In [1]:
#q2

In [3]:
import numpy as np

In [5]:
A = np.array([[1,0,1],
              [0,1,1],
              [1,1,0]])

In [17]:
np.linalg.inv(A)

array([[ 0.5, -0.5,  0.5],
       [-0.5,  0.5,  0.5],
       [ 0.5,  0.5, -0.5]])

In [20]:
#q3

In [22]:
import time

In [50]:
start = time.time()

In [52]:
end = time.time()

In [54]:
end - start

0.11880993843078613

In [72]:
#time.time()调用从世界基准点 1970,1,1 00:00:00 到现在有多少秒
time.time()

1757683577.750892

In [76]:
time.time()/60/60/24 #多少天

20343.56022272867

In [120]:
np.random.seed(88)

In [122]:
A = np.random.randint(1,10,(5,5))
A

array([[9, 1, 2, 5, 6],
       [2, 1, 6, 1, 3],
       [2, 5, 8, 8, 8],
       [7, 7, 4, 2, 1],
       [9, 7, 1, 1, 6]])

In [124]:
B = np.random.randint(1,10,(10,10))
B

array([[8, 6, 4, 6, 4, 8, 4, 4, 9, 6],
       [1, 7, 5, 1, 3, 3, 6, 3, 6, 7],
       [7, 2, 2, 9, 7, 2, 3, 2, 8, 5],
       [4, 7, 7, 7, 1, 4, 1, 9, 3, 8],
       [1, 8, 3, 7, 4, 7, 9, 7, 5, 4],
       [3, 8, 2, 4, 9, 9, 1, 9, 6, 1],
       [5, 5, 1, 2, 5, 2, 8, 8, 1, 8],
       [2, 1, 1, 7, 5, 8, 7, 9, 6, 4],
       [5, 2, 1, 3, 7, 2, 1, 3, 1, 8],
       [8, 4, 2, 9, 8, 9, 2, 4, 2, 6]])

In [128]:
def get_minor(matrix,row,col):
    """
    提取余子矩阵,去掉指定的行和列
    """
    return np.delete(np.delete(matrix,row,axis = 0),col,axis = 1)

In [131]:
def determinant(matrix):
    """
    递归计算行列式 (Laplace 展开)
    """
    n = matrix.shape[0]
    if n == 1:
        return matrix[0,0]
    if n ==2:
        return matrix[0,0]*matrix[1,1] - matrix[0,1]*matrix[1,0]

    det = 0
    for col in range(n):
        minor = get_minor(matrix,0,col)
        cofactor = ((-1) ** col) * determinant(minor)
        det += matrix[0,col] * cofactor

    return det

In [134]:
def cofactor_matrix(matrix):
    """
    计算代数余子式矩阵
    """
    n = matrix.shape[0]
    cof_matrix = np.zeros((n,n))

    for row in range(n):
        for col in range(n):
            minor = get_minor(matrix,row,col)
            cof_matrix[row,col] = ((-1) ** (row+col)) * determinant(minor)

    return cof_matrix

In [137]:
def adjugate_matrix(matrix):
    """
    计算伴随矩阵,代数余子式矩阵的转置
    """
    return cofactor_matrix(matrix).T

In [140]:
def inverse_matrix(matrix):
    """
    计算矩阵的逆矩阵(如果存在)
    """
    det = determinant(matrix)
    if det == 0:
        raise ValueError('矩阵不可逆,行列式为0')

    adj = adjugate_matrix(matrix)
    return adj/det

In [147]:
start = time.time()
print(np.linalg.inv(A))
end = time.time()
end - start

[[ 0.09724104  0.03516443 -0.07691834  0.05795049 -0.02192388]
 [-0.11023525 -0.09052839  0.05616455  0.0609681   0.07045203]
 [-0.01391797  0.1729277  -0.01748984  0.04680379 -0.05702673]
 [ 0.08812662 -0.17902451  0.08861929  0.0797512  -0.13006528]
 [-0.02962187  0.05388595  0.03799729 -0.17914768  0.14854046]]


0.013947725296020508

In [151]:
start = time.time()
print(inverse_matrix(A))
end = time.time()
end - start

[[ 0.09724104  0.03516443 -0.07691834  0.05795049 -0.02192388]
 [-0.11023525 -0.09052839  0.05616455  0.0609681   0.07045203]
 [-0.01391797  0.1729277  -0.01748984  0.04680379 -0.05702673]
 [ 0.08812662 -0.17902451  0.08861929  0.0797512  -0.13006528]
 [-0.02962187  0.05388595  0.03799729 -0.17914768  0.14854046]]


0.01395106315612793

In [153]:
start = time.time()
print(np.linalg.inv(B))
end = time.time()
end - start

[[ 0.02128415  0.03038654  0.05143654 -0.00123994 -0.16629995  0.01194327
   0.1598788  -0.03311189 -0.22639019  0.12168689]
 [ 0.13287547 -0.18197973 -0.05277408 -0.00333811  0.26436151  0.01981187
  -0.05816297 -0.15741521  0.22286846 -0.16634339]
 [-0.36301455  0.51293475  0.15322026  0.06831176 -0.50312411  0.04411179
   0.17479065  0.09717291 -0.65990479  0.45592581]
 [ 0.00399686 -0.13225141  0.03882404  0.0355786   0.17239395 -0.04473156
  -0.08558958 -0.02884487  0.11248409 -0.05359853]
 [-0.19918707  0.19392079  0.09343581 -0.0373232  -0.16455972  0.07342671
   0.05663797  0.0255039  -0.15997615  0.16309758]
 [ 0.07154051  0.00606452 -0.117341   -0.03082506  0.01102157 -0.01538224
  -0.06613471  0.0512929   0.04345393  0.05153024]
 [-0.10243203  0.14932273  0.0528314  -0.04390993 -0.09721408 -0.02704012
   0.12618187  0.03455959 -0.24494961  0.14737593]
 [-0.01519589 -0.04874594  0.00283962  0.05566321 -0.05386229  0.04639342
   0.06378044  0.05049828 -0.03228527 -0.05200094]


0.09809994697570801

In [155]:
start = time.time()
print(inverse_matrix(B))
end = time.time()
end - start

[[ 0.02128415  0.03038654  0.05143654 -0.00123994 -0.16629995  0.01194327
   0.1598788  -0.03311189 -0.22639019  0.12168689]
 [ 0.13287547 -0.18197973 -0.05277408 -0.00333811  0.26436151  0.01981187
  -0.05816297 -0.15741521  0.22286846 -0.16634339]
 [-0.36301455  0.51293475  0.15322026  0.06831176 -0.50312411  0.04411179
   0.17479065  0.09717291 -0.65990479  0.45592581]
 [ 0.00399686 -0.13225141  0.03882404  0.0355786   0.17239395 -0.04473156
  -0.08558958 -0.02884487  0.11248409 -0.05359853]
 [-0.19918707  0.19392079  0.09343581 -0.0373232  -0.16455972  0.07342671
   0.05663797  0.0255039  -0.15997615  0.16309758]
 [ 0.07154051  0.00606452 -0.117341   -0.03082506  0.01102157 -0.01538224
  -0.06613471  0.0512929   0.04345393  0.05153024]
 [-0.10243203  0.14932273  0.0528314  -0.04390993 -0.09721408 -0.02704012
   0.12618187  0.03455959 -0.24494961  0.14737593]
 [-0.01519589 -0.04874594  0.00283962  0.05566321 -0.05386229  0.04639342
   0.06378044  0.05049828 -0.03228527 -0.05200094]


113.17054581642151