In [1]:
#q1

In [78]:
import numpy as np

In [80]:
np.random.seed(0)
n_samples = 100

X_vecs = np.random.randn(n_samples,6)

y = X_vecs @ np.array([[-3],[2],[-2],[3],[1],[-1]])
#1D数组与列向量相加,广播中会默认看成行向量导致列向量列方向广播,1D数组行方向广播
y = y + 1 + 0.25*np.random.randn(n_samples,1)

In [82]:
y.shape

(100, 1)

In [84]:
X = np.column_stack((np.ones_like(y),X_vecs))

In [86]:
X.shape

(100, 7)

In [92]:
b = np.linalg.inv(X.T @ X) @ X.T @ y
b

array([[ 0.96195899],
       [-2.98149001],
       [ 2.02061166],
       [-1.99327202],
       [ 3.05484756],
       [ 0.98370887],
       [-1.01352482]])

In [98]:
y_hat = X @ b
y_hat.shape

(100, 1)

In [100]:
epsilon = y - y_hat
epsilon.shape

(100, 1)

In [103]:
#Q2

In [131]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [133]:
np.random.seed(0)
n_samples = 100

X_vecs = np.random.randn(n_samples,6)

y = X_vecs @ np.array([[-3],[2],[-2],[3],[1],[-1]])
#1D数组与列向量相加,广播中会默认看成行向量导致列向量列方向广播,1D数组行方向广播
y = y + 1 + 0.25*np.random.randn(n_samples,1)

In [125]:
LR = LinearRegression()

In [137]:
LR.fit(X_vecs,y)

LinearRegression()

In [142]:
slope = LR.coef_
slope

array([[-2.98149001,  2.02061166, -1.99327202,  3.05484756,  0.98370887,
        -1.01352482]])

In [147]:
intercept = LR.intercept_
intercept

array([0.96195899])

In [170]:
#intercept自动视为一列,slope视为6列
b_LR = np.column_stack((intercept,slope))
b_LR = b_LR.T
b_LR

array([[ 0.96195899],
       [-2.98149001],
       [ 2.02061166],
       [-1.99327202],
       [ 3.05484756],
       [ 0.98370887],
       [-1.01352482]])

In [175]:
y_hat = LR.predict(X_vecs)
y_hat.shape

(100, 1)

In [178]:
epsilen = y - y_hat
epsilen.shape

(100, 1)