In [2]:
import numpy as np
from scipy.linalg import lu

In [4]:
A = np.array([[2,5,8,7],
              [5,2,2,8],
              [7,5,6,6],
              [5,4,4,8]])

In [6]:
p,l,u = lu(A)

In [8]:
np.allclose(A,p@l@u)

True

In [10]:
p

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [12]:
p,_,_ = lu(A,p_indices = True)

In [14]:
p

array([1, 3, 0, 2], dtype=int32)

In [16]:
np.allclose(A,l[p,:]@u)

True

In [26]:
rng = np.random.default_rng()

In [28]:
A = rng.uniform(low = -4,high = 4,size = [3,2,4,8])
p,l,u = lu(A)

In [30]:
p.shape,l.shape,u.shape

((3, 2, 4, 4), (3, 2, 4, 4), (3, 2, 4, 8))

In [34]:
np.allclose(A,p@l@u)

True

In [36]:
PL,U = lu(A,permute_l = True)
np.allclose(A,PL@U)

True

In [38]:
import numpy as np

In [40]:
from scipy.linalg import ldl

In [42]:
a = np.array([[2,-1,3],
              [0,2,0],
              [0,0,1]])

In [44]:
lu,d,perm = ldl(a,lower = 0)

In [46]:
lu

array([[ 0. ,  0. ,  1. ],
       [ 0. ,  1. , -0.5],
       [ 1. ,  1. ,  1.5]])

In [48]:
d

array([[-5. ,  0. ,  0. ],
       [ 0. ,  1.5,  0. ],
       [ 0. ,  0. ,  2. ]])

In [50]:
perm

array([2, 1, 0])

In [52]:
lu[perm,:]

array([[ 1. ,  1. ,  1.5],
       [ 0. ,  1. , -0.5],
       [ 0. ,  0. ,  1. ]])

In [54]:
lu.dot(d).dot(lu.T)

array([[ 2., -1.,  3.],
       [-1.,  2.,  0.],
       [ 3.,  0.,  1.]])