In [2]:
#q1

In [6]:
import numpy as np

In [8]:
def matrix_multiplication_outer(A,B):
    #获取形状
    m,p_A = A.shape
    p_B,n = B.shape

    #检查形状是否匹配
    if p_A != p_B:
        raise ValueError('Dimensions do not match')

    #初始化结果矩阵
    C = np.zeros((m,n))

    for k in range(p_A):
        a_k = A[:,[k]]
        b_k = B[[k],:]
        C += (a_k @ b_k)
        
    return C

In [10]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[1,3],
              [2,4]])

In [12]:
matrix_multiplication_outer(A,B)

array([[ 5., 11.],
       [11., 25.]])

In [14]:
A = np.array([[1,0],
              [3,1]])
B = np.array([[1,0],
              [2,1]])

In [16]:
matrix_multiplication_outer(A,B)

array([[1., 0.],
       [5., 1.]])

In [18]:
A = np.array([[1,1],
              [0,1]])
B = np.array([[1,3],
              [0,1]])
matrix_multiplication_outer(A,B)

array([[1., 4.],
       [0., 1.]])

In [20]:
A = np.array([[1,2],
              [3,4],
              [5,6]])
B = A.T
matrix_multiplication_outer(A,B)

array([[ 5., 11., 17.],
       [11., 25., 39.],
       [17., 39., 61.]])

In [22]:
#q2