In [1]:
#q1

In [5]:
import numpy as np

In [9]:
a = np.array([[1],
              [2]])
a

array([[1],
       [2]])

In [11]:
a_T = a.T
a_T

array([[1, 2]])

In [13]:
a_T @ a

array([[5]])

In [15]:
a @ a_T

array([[1, 2],
       [2, 4]])

In [17]:
#q2

In [19]:
a = np.array([[1],
              [2]])
a

array([[1],
       [2]])

In [21]:
a_T = a.T
a_T

array([[1, 2]])

In [23]:
b = np.array([[1],
              [2],
              [3]])
b

array([[1],
       [2],
       [3]])

In [25]:
b_T = b.T
b_T

array([[1, 2, 3]])

In [27]:
a @ b_T

array([[1, 2, 3],
       [2, 4, 6]])

In [29]:
b @ a_T

array([[1, 2],
       [2, 4],
       [3, 6]])

In [31]:
#q3

In [33]:
A = np.array([[1,2],
              [3,4]])
b = np.array([[1],
              [2]])

In [35]:
A_T = A.T
b_T = b.T

In [39]:
A @ b

array([[ 5],
       [11]])

In [41]:
b_T @ A_T

array([[ 5, 11]])

In [43]:
#q4

In [45]:
A = np.array([[1,2],
              [3,4],
              [5,6]])
A_T = A.T

In [47]:
A@A.T

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [51]:
A.T @ A

array([[35, 44],
       [44, 56]])

In [53]:
#q5

In [56]:
def matrix_multiplication_inner(A, B):
    
    # 获取矩阵 A 和 B 的形状
    m, p_A = A.shape
    p_B, n = B.shape

    # 检测矩阵形状是否符合矩阵乘法规则
    if p_A != p_B:
        raise ValueError('Dimensions do not match')

    # 初始化结果矩阵 C，形状 (m, n)，初始值设为 0
    C = np.zeros((m, n))

    # 计算每个元素
    for j in range(n):
        for i in range(m):
            row_i_A = A[i, :]        # A 的第 i 行（行向量）
            col_j_B = B[:, j]        # B 的第 j 列（列向量）
            C[i, j] = np.dot(row_i_A, col_j_B)  # 计算内积

    return C

In [58]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
B = A.T
B

array([[1, 4],
       [2, 5],
       [3, 6]])

In [62]:
matrix_multiplication_inner(A, B)

array([[14., 32.],
       [32., 77.]])

In [64]:
matrix_multiplication_inner(B, A)

array([[17., 22., 27.],
       [22., 29., 36.],
       [27., 36., 45.]])