In [1]:
#q2

In [3]:
import numpy as np

In [81]:
def matrix_equality(A,B):
    m,p = A.shape
    q,n = B.shape

    if p == q:
    #A@B
        AB = np.zeros((m,n))
        for i in range(m):
            for j in range(n):
                for k in range(p):
                    AB[i,j] += A[i,k] * B[k,j]

    if m == n:
        #B@A
        BA = np.zeros((q,p))
        for i in range(q):
            for j in range(p):
                for k in range(n):
                    BA[i,j] += B[i,k] * A[k,j]

    return np.array_equal(AB,BA)

In [83]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

In [85]:
matrix_equality(A,B)

False

In [87]:
A = np.array([[1,2]])
B = np.array([[3],
     [4]])

In [89]:
matrix_equality(A,B)

False

In [91]:
A = np.array([[1,0],
              [0,1]])
B = np.array([[2,3],
              [4,5]])

In [93]:
matrix_equality(A,B)

True

In [95]:
A = np.array([[1,2],
              [2,1]])
B = np.array([[3,4],
              [4,3]])

In [97]:
matrix_equality(A,B)

True

In [99]:
A = np.array([[1,1],
              [1,1]])
B = np.array([[2,2],
              [2,2]])

In [101]:
matrix_equality(A,B)

True

In [103]:
A = np.array([[1,0],
              [0,2]])
B = np.array([[3,0],
              [0,4]])

In [105]:
matrix_equality(A,B)

True

In [109]:
A = np.array([[np.cos(np.pi/6), - np.sin(np.pi/6)],
              [np.sin(np.pi/6), np.cos(np.pi/6)]])
B = np.array([[np.cos(np.pi/3), - np.sin(np.pi/3)],
              [np.sin(np.pi/3), np.cos(np.pi/3)]])

In [111]:
matrix_equality(A,B)

True

In [113]:
A = np.array([[np.cos(np.pi/3), - np.sin(np.pi/3)],
              [np.sin(np.pi/3), np.cos(np.pi/3)]])
B = np.array([[np.cos(np.pi/4), - np.sin(np.pi/4)],
              [np.sin(np.pi/4), np.cos(np.pi/4)]])

In [115]:
matrix_equality(A,B)

True

In [117]:
A = np.array([[1,1],
              [0,1]])
B = np.array([[1,2],
              [0,1]])

In [119]:
matrix_equality(A,B)

True

In [121]:
A = np.array([[1,0],
              [1,1]])
B = np.array([[1,0],
              [2,1]])

In [123]:
matrix_equality(A,B)

True

In [125]:
#q3

In [127]:
a = np.array([[1],
              [2]])
a_T = a.T

In [129]:
a@a.T

array([[1, 2],
       [2, 4]])

In [131]:
a.T@a

array([[5]])

In [133]:
#q4

In [139]:
a = np.array([[1],
           [2]])
b = np.array([[1],
           [2],
           [3]])
a_T = a.T;b_T = b.T

In [141]:
a@b_T

array([[1, 2, 3],
       [2, 4, 6]])

In [143]:
b@a_T

array([[1, 2],
       [2, 4],
       [3, 6]])

In [145]:
#q5

In [147]:
A = np.array([[1,2],
              [3,4]])
b = np.array([[1],
              [2]])

In [149]:
A@b

array([[ 5],
       [11]])

In [151]:
b.T@A

array([[ 7, 10]])

In [153]:
#q6

In [155]:
A = np.array([[1,2],
              [3,4],
              [5,6]])

In [157]:
A@A.T

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [159]:
A.T@A

array([[35, 44],
       [44, 56]])

In [161]:
#q7

In [163]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[1,4],
              [2,5],
              [3,6]])

In [165]:
m,pb = b.shape
pa,n = a.shape

In [177]:
for i in range(m):
    for j in range(n):
        d = 0
        for k in range(pb):
            d += b[i,k]*a[k,j]
        print(d)

17
22
27
22
29
36
27
36
45


In [179]:
#q8

In [182]:
def matrix_multiplication(A,B):
    #获取形状
    m,p_A = A.shape 
    p_B,n = B.shape
    if p_A != p_B:
        raise ValueError('Dimensions do not match')

    C = np.zeros((m,n))
    
    for j in range(n):
        for i in range(m):
            for k in range(p_A):
                C[i,j] += A[i,k] * B[k,j]
    return C                

In [185]:
A = np.array([[1,2,3],
              [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [188]:
B = A.T
B

array([[1, 4],
       [2, 5],
       [3, 6]])

In [191]:
matrix_multiplication(A,B)

array([[14., 32.],
       [32., 77.]])

In [194]:
matrix_multiplication(B,A)

array([[17., 22., 27.],
       [22., 29., 36.],
       [27., 36., 45.]])