In [1]:
import numpy as np

In [4]:
A = np.array([[0,1],
              [1,1],
              [1,0]])
G_1 = A.T @ A
G_2 = A @ A.T

lambdas_G_1,V_G_1 = np.linalg.eigh(G_1)
lambdas_G_2,U_G_2 = np.linalg.eigh(G_2)
print(lambdas_G_1)
print(V_G_1)
print(lambdas_G_2)
print(U_G_2)

[1. 3.]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
[2.56090598e-16 1.00000000e+00 3.00000000e+00]
[[-5.77350269e-01  7.07106781e-01  4.08248290e-01]
 [ 5.77350269e-01  9.13969213e-18  8.16496581e-01]
 [-5.77350269e-01 -7.07106781e-01  4.08248290e-01]]


In [8]:
U,S,V_T = np.linalg.svd(A,full_matrices = False)
print(U)
print(S)
print(V_T)

[[-4.08248290e-01  7.07106781e-01]
 [-8.16496581e-01  7.45552182e-17]
 [-4.08248290e-01 -7.07106781e-01]]
[1.73205081 1.        ]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [32]:
A_hat = U[:,[0]]*S[0]@V_T[[0],:]
A_hat

array([[0.5, 0.5],
       [1. , 1. ],
       [0.5, 0.5]])

In [36]:
A - X_hat

array([[-5.00000000e-01,  5.00000000e-01],
       [ 2.22044605e-16,  4.44089210e-16],
       [ 5.00000000e-01, -5.00000000e-01]])