In [2]:
import numpy as np

In [24]:
A = np.array([[5/4,-3/4],
              [-3/4,5/4]])
G_1 = A.T @ A
G_2 = A @ A.T

lambdas_G_1,V_G_1 = np.linalg.eigh(G_1)
lambdas_G_2,U_G_2 = np.linalg.eigh(G_2)
print(lambdas_G_1)
print(V_G_1)
print(lambdas_G_2)
print(U_G_2)

print('')

U,S,V_T = np.linalg.svd(A)
print(U)
print(S)
print(V_T)

[0.25 4.  ]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[0.25 4.  ]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
[2.  0.5]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


In [26]:
A = np.array([[2,1],
              [0,1]])
G_1 = A.T @ A
G_2 = A @ A.T

lambdas_G_1,V_G_1 = np.linalg.eigh(G_1)
lambdas_G_2,U_G_2 = np.linalg.eigh(G_2)
print(lambdas_G_1)
print(V_G_1)
print(lambdas_G_2)
print(U_G_2)

print('')

U,S,V_T = np.linalg.svd(A)
print(U)
print(S)
print(V_T)

[0.76393202 5.23606798]
[[ 0.52573111 -0.85065081]
 [-0.85065081 -0.52573111]]
[0.76393202 5.23606798]
[[ 0.22975292 -0.97324899]
 [-0.97324899 -0.22975292]]

[[ 0.97324899 -0.22975292]
 [ 0.22975292  0.97324899]]
[2.28824561 0.87403205]
[[ 0.85065081  0.52573111]
 [-0.52573111  0.85065081]]


In [28]:
A = np.array([[0,1,1],
              [1,0,1],
              [1,1,0]])
G_1 = A.T @ A
G_2 = A @ A.T

lambdas_G_1,V_G_1 = np.linalg.eigh(G_1)
lambdas_G_2,U_G_2 = np.linalg.eigh(G_2)
print(lambdas_G_1)
print(V_G_1)
print(lambdas_G_2)
print(U_G_2)

print('')

U,S,V_T = np.linalg.svd(A)
print(U)
print(S)
print(V_T)

[1. 1. 4.]
[[ 0.57307506 -0.58159406  0.57735027]
 [-0.79021276 -0.20550053  0.57735027]
 [ 0.2171377   0.78709459  0.57735027]]
[1. 1. 4.]
[[ 0.57307506 -0.58159406  0.57735027]
 [-0.79021276 -0.20550053  0.57735027]
 [ 0.2171377   0.78709459  0.57735027]]

[[-5.77350269e-01 -1.00875766e-16  8.16496581e-01]
 [-5.77350269e-01 -7.07106781e-01 -4.08248290e-01]
 [-5.77350269e-01  7.07106781e-01 -4.08248290e-01]]
[2. 1. 1.]
[[-0.57735027 -0.57735027 -0.57735027]
 [-0.          0.70710678 -0.70710678]
 [-0.81649658  0.40824829  0.40824829]]


In [30]:
A = np.array([[0,1,-1],
              [1,0,1],
              [1,1,0]])
G_1 = A.T @ A
G_2 = A @ A.T

lambdas_G_1,V_G_1 = np.linalg.eigh(G_1)
lambdas_G_2,U_G_2 = np.linalg.eigh(G_2)
print(lambdas_G_1)
print(V_G_1)
print(lambdas_G_2)
print(U_G_2)

print('')

U,S,V_T = np.linalg.svd(A)
print(U)
print(S)
print(V_T)

[-1.00582367e-17  3.00000000e+00  3.00000000e+00]
[[-0.57735027 -0.50766227  0.63948861]
 [ 0.57735027 -0.80764452 -0.11990412]
 [ 0.57735027  0.29998225  0.75939273]]
[-1.00582367e-17  3.00000000e+00  3.00000000e+00]
[[ 0.57735027 -0.50766227  0.63948861]
 [ 0.57735027  0.80764452  0.11990412]
 [-0.57735027  0.29998225  0.75939273]]

[[ 0.          0.81649658 -0.57735027]
 [-0.70710678 -0.40824829 -0.57735027]
 [-0.70710678  0.40824829  0.57735027]]
[1.73205081e+00 1.73205081e+00 7.75799640e-17]
[[-8.16496581e-01 -4.08248290e-01 -4.08248290e-01]
 [ 2.89172142e-17  7.07106781e-01 -7.07106781e-01]
 [-5.77350269e-01  5.77350269e-01  5.77350269e-01]]


In [32]:
A = np.array([[0,1,1],
              [1,1,0]])
G_1 = A.T @ A
G_2 = A @ A.T

lambdas_G_1,V_G_1 = np.linalg.eigh(G_1)
lambdas_G_2,U_G_2 = np.linalg.eigh(G_2)
print(lambdas_G_1)
print(V_G_1)
print(lambdas_G_2)
print(U_G_2)

print('')

U,S,V_T = np.linalg.svd(A)
print(U)
print(S)
print(V_T)

[2.56090598e-16 1.00000000e+00 3.00000000e+00]
[[-5.77350269e-01  7.07106781e-01  4.08248290e-01]
 [ 5.77350269e-01  9.13969213e-18  8.16496581e-01]
 [-5.77350269e-01 -7.07106781e-01  4.08248290e-01]]
[1. 3.]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[1.73205081 1.        ]
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [ 7.07106781e-01  1.65204549e-16 -7.07106781e-01]
 [ 5.77350269e-01 -5.77350269e-01  5.77350269e-01]]


In [34]:
A = np.array([[0,1,1],
              [0,-1,-1]])
G_1 = A.T @ A
G_2 = A @ A.T

lambdas_G_1,V_G_1 = np.linalg.eigh(G_1)
lambdas_G_2,U_G_2 = np.linalg.eigh(G_2)
print(lambdas_G_1)
print(V_G_1)
print(lambdas_G_2)
print(U_G_2)

print('')

U,S,V_T = np.linalg.svd(A)
print(U)
print(S)
print(V_T)

[0. 0. 4.]
[[ 1.          0.          0.        ]
 [ 0.         -0.70710678  0.70710678]
 [ 0.          0.70710678  0.70710678]]
[0. 4.]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
[2.00000000e+00 1.77302319e-16]
[[ 8.86511593e-17 -7.07106781e-01 -7.07106781e-01]
 [ 1.00000000e+00 -9.43234100e-17 -9.43234100e-17]
 [-1.00875766e-16 -7.07106781e-01  7.07106781e-01]]
