In [1]:
import numpy as np

In [21]:
X = np.array([[1,1,1,1],
             [1,2,3,4]]).T
X

array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4]])

In [23]:
y_hat = np.array([[2,1,4,3]]).T
y_hat

array([[2],
       [1],
       [4],
       [3]])

In [31]:
X.T@X 

array([[ 4, 10],
       [10, 30]])

In [35]:
np.linalg.det(X.T@X) #检查是否可逆

20.000000000000014

In [39]:
np.linalg.inv(X.T@X )

array([[ 1.5, -0.5],
       [-0.5,  0.2]])

In [25]:
np.linalg.inv(X.T@X) @ X.T @ X

array([[ 1.00000000e+00, -1.55431223e-15],
       [ 2.22044605e-16,  1.00000000e+00]])

In [37]:
b = np.linalg.inv(X.T@X) @ X.T @ y_hat
b

array([[1. ],
       [0.6]])

In [42]:
#q2

In [125]:
import numpy as np

In [127]:
np.random.seed(0)

In [129]:
#rand是生成0-1之间的均匀随机数 然后再放大10倍变成范围为0-10
#0-1是数学上的标准化随机数范围,然后再按需线性变换区间或分布
x = np.random.rand(50)*10 
x

array([5.48813504, 7.15189366, 6.02763376, 5.44883183, 4.23654799,
       6.45894113, 4.37587211, 8.91773001, 9.63662761, 3.83441519,
       7.91725038, 5.2889492 , 5.68044561, 9.25596638, 0.71036058,
       0.871293  , 0.20218397, 8.32619846, 7.78156751, 8.70012148,
       9.78618342, 7.99158564, 4.61479362, 7.80529176, 1.18274426,
       6.39921021, 1.43353287, 9.44668917, 5.21848322, 4.1466194 ,
       2.64555612, 7.74233689, 4.56150332, 5.68433949, 0.187898  ,
       6.17635497, 6.12095723, 6.16933997, 9.43748079, 6.81820299,
       3.59507901, 4.37031954, 6.97631196, 0.60225472, 6.66766715,
       6.7063787 , 2.10382561, 1.28926298, 3.15428351, 3.63710771])

In [131]:
true_slope = 0.8

In [133]:
true_intercept = 2

In [135]:
noise = np.random.rand(50)*2-1  #生成[-1,1]之间的均匀随机数
noise

array([ 0.14039354, -0.12279697,  0.97674768, -0.79591038, -0.58224649,
       -0.67738096,  0.30621665, -0.49341679, -0.06737845, -0.51114882,
       -0.68206083, -0.77924972,  0.31265918, -0.7236341 , -0.60683528,
       -0.26254966,  0.64198646, -0.80579745,  0.67588981, -0.80780318,
        0.95291893, -0.0626976 ,  0.95352218,  0.20969104,  0.47852716,
       -0.92162442, -0.43438607, -0.75960688, -0.4077196 , -0.76254456,
       -0.36403364, -0.17147401, -0.87170501,  0.38494424,  0.13320291,
       -0.46922102,  0.04649611, -0.81211898,  0.15189299,  0.8585924 ,
       -0.3628621 ,  0.33482076, -0.73640428,  0.43265441, -0.42118781,
       -0.63361728,  0.17302587, -0.95978491,  0.65788006, -0.99060905])

In [137]:
y = true_slope*x + true_intercept + noise
y

array([ 6.53090157,  7.59871796,  7.79885468,  5.56315509,  4.80699191,
        6.48977194,  5.80691434,  8.64076721,  9.64192363,  4.55638333,
        7.65173947,  5.45190964,  6.85701567,  8.68113901,  1.96145319,
        2.43448474,  2.80373364,  7.85516132,  8.90114382,  8.152294  ,
       10.78186567,  8.33057092,  6.64535707,  8.45392445,  3.42472257,
        6.19774376,  2.71244022,  8.79774446,  5.76706697,  4.55475096,
        3.75241126,  8.0223955 ,  4.77749765,  6.93241583,  2.28352131,
        6.47186296,  6.94326189,  6.123353  ,  9.70187762,  8.31315479,
        4.51320111,  5.83107639,  6.84464529,  2.91445818,  6.91294591,
        6.73148568,  3.85608636,  2.07162547,  5.18130687,  3.91907712])

In [139]:
X = np.column_stack((np.ones_like(x),x))

In [141]:
b = np.linalg.inv(X.T@X)@X.T@y
b

array([1.91610418, 0.78125175])

In [143]:
y_hat = X@b

In [147]:
noise_new = y - y_hat
noise_new

array([ 0.3271823 ,  0.09518436,  1.1736511 , -0.60985848, -0.4189228 ,
       -0.47239129,  0.47215243, -0.24232912,  0.19718729, -0.35536441,
       -0.4497304 , -0.59619534,  0.50305343, -0.46620508, -0.50962144,
       -0.16231862,  0.72967287, -0.56579996,  0.90567643, -0.56079529,
        1.22028859,  0.17102649,  1.12393731,  0.43992244,  0.58459737,
       -0.71775459, -0.32361402, -0.49860214, -0.22598634, -0.60090688,
       -0.23053827,  0.0575771 , -0.70228897,  0.57541149,  0.22062149,
       -0.26952934,  0.24514918, -0.61255882,  0.41272508,  1.07031761,
       -0.21156483,  0.50065243, -0.5217148 ,  0.52784145, -0.21228489,
       -0.42398857,  0.29636474, -0.85171766,  0.80091318, -0.83852381])