In [1]:
import numpy as np

In [3]:
#q1

In [5]:
A = np.array([[1,1],
              [0,1]])

In [10]:
lambdas,V = np.linalg.eig(A)

In [13]:
lambdas

array([1., 1.])

In [15]:
V

array([[ 1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  2.22044605e-16]])

In [17]:
A = np.array([[2,0],
              [0,2]])

In [19]:
lambdas,V = np.linalg.eig(A)

In [21]:
lambdas

array([2., 2.])

In [23]:
V

array([[1., 0.],
       [0., 1.]])