In [1]:
import numpy as np

In [20]:
A = np.array([[0,1],
              [1,1],
              [1,0]])
G_1 = A.T @ A
G_2 = A @ A.T

lambdas_G_1,V_G_1 = np.linalg.eigh(G_1)
lambdas_G_2,U_G_2 = np.linalg.eigh(G_2)
print(lambdas_G_1)
print(V_G_1)
print(lambdas_G_2)
print(U_G_2)

print('')

U,S,V_T = np.linalg.svd(A)
print(U)
print(S)
print(V_T)

[1. 3.]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
[2.56090598e-16 1.00000000e+00 3.00000000e+00]
[[-5.77350269e-01  7.07106781e-01  4.08248290e-01]
 [ 5.77350269e-01  9.13969213e-18  8.16496581e-01]
 [-5.77350269e-01 -7.07106781e-01  4.08248290e-01]]

[[-4.08248290e-01  7.07106781e-01  5.77350269e-01]
 [-8.16496581e-01  7.45552182e-17 -5.77350269e-01]
 [-4.08248290e-01 -7.07106781e-01  5.77350269e-01]]
[1.73205081 1.        ]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [22]:
print(G_1)
print(G_2)

[[2 1]
 [1 2]]
[[1 1 0]
 [1 2 1]
 [0 1 1]]


In [10]:
U,S,V_T = np.linalg.svd(A,full_matrices = False)
print(U)
print(S)
print(V_T)

[[-4.08248290e-01  7.07106781e-01]
 [-8.16496581e-01  7.45552182e-17]
 [-4.08248290e-01 -7.07106781e-01]]
[1.73205081 1.        ]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [14]:
#Q2

In [24]:
A = np.array([[0,0],
              [1,-1],
              [1,-1]])
G_1 = A.T @ A
G_2 = A @ A.T

lambdas_G_1,V_G_1 = np.linalg.eigh(G_1)
lambdas_G_2,U_G_2 = np.linalg.eigh(G_2)
print(lambdas_G_1)
print(V_G_1)
print(lambdas_G_2)
print(U_G_2)

[0. 4.]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[0. 0. 4.]
[[ 1.          0.          0.        ]
 [ 0.         -0.70710678  0.70710678]
 [ 0.          0.70710678  0.70710678]]


In [26]:
print(G_1)
print(G_2)

[[ 2 -2]
 [-2  2]]
[[0 0 0]
 [0 2 2]
 [0 2 2]]


In [16]:
U,S,V_T = np.linalg.svd(A)
print(U)
print(S)
print(V_T)

[[ 8.86511593e-17  1.00000000e+00 -1.00875766e-16]
 [-7.07106781e-01 -9.43234100e-17 -7.07106781e-01]
 [-7.07106781e-01 -9.43234100e-17  7.07106781e-01]]
[2.00000000e+00 1.77302319e-16]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


In [18]:
U,S,V_T = np.linalg.svd(A,full_matrices = False)
print(U)
print(S)
print(V_T)

[[ 8.86511593e-17  1.00000000e+00]
 [-7.07106781e-01 -9.43234100e-17]
 [-7.07106781e-01 -9.43234100e-17]]
[2.00000000e+00 1.77302319e-16]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
