In [1]:
#q1

In [3]:
import numpy as np

In [27]:
A = np.random.randint(0,10,(2,2))
B = np.random.randint(0,10,(2,2))
C = np.random.randint(0,10,(2,2))
D = np.random.randint(0,10,(2,2))
#分配名字,打印方便
mats = [('A',A),('B',B),('C',C),('D',D)]

In [13]:
def perms(items):
    if not items:
        return[[]]
    res = []

    for i in range(len(items)):
        #取出第i索引元素
        head = items[i]
        #取出除了i索引元素外的所有元素
        tail = items[:i] + items[i+1:]
        #对剩下的元素做全排列 perms返回的类型是列表
        for p in perms(tail):
            #i索引元素放在前面
            #这里的加法不是矩阵加法,是列表拼接所以给head带上[]表示列表,然后拼接
            res.append([head] + p)
    return res

In [15]:
def chain_product(seq):#输入的是一种顺序的组合
    #两个[]表示取两次索引第一次取列表中的元组,第二次取元组中的元素(那个大写的变量,是一个array数组)
    M = seq[0][1]
    #这里将元组取出 从除了输入元组的i为1开始取,不与上面重叠
    #_是一个变量名,但是这里没用,渐渐习惯成不用的变量附在这个变量吗上  这里被赋值的是name,但是不用
    #mat是实际的array数组赋值
    for _,mat in seq[1:]:
        #矩阵乘法按照顺序连乘
        M = M@mat
    return M

In [19]:
all_orders = perms(mats)
print('总排列数:',len(all_orders))

总排列数: 24


In [25]:
for seq in all_orders:
    #join表示链接符号,用恰面的字符串作为链接符号,加入到join中的给出的字符串形成新的字符串
    order_str = '@'.join(name for name,_ in seq)
    #计算
    prod = chain_product(seq)
    print(order_str)
    print(prod,'\n')

A@B@C@D
[[2592 2118]
 [6324 5256]] 

A@B@D@C
[[3012 1498]
 [6828 3472]] 

A@C@B@D
[[1852 1858]
 [3450 3585]] 

A@C@D@B
[[1752 1398]
 [2964 2496]] 

A@D@B@C
[[3702 1988]
 [9270 5040]] 

A@D@C@B
[[2272 2178]
 [5340 5220]] 

B@A@C@D
[[2160 1380]
 [3102 2088]] 

B@A@D@C
[[4776 2044]
 [6234 2716]] 

B@C@A@D
[[1932 2268]
 [5700 6810]] 

B@C@D@A
[[1008 2100]
 [3174 6840]] 

B@D@A@C
[[4002 1246]
 [4425 1435]] 

B@D@C@A
[[1704 3340]
 [2370 4780]] 

C@A@B@D
[[5398 4387]
 [1284 1086]] 

C@A@D@B
[[7596 4974]
 [1704 1146]] 

C@B@A@D
[[5344 6421]
 [1752 2148]] 

C@B@D@A
[[3037 6610]
 [1068 2400]] 

C@D@A@B
[[7224 3918]
 [1092  624]] 

C@D@B@A
[[3048 6420]
 [ 534 1200]] 

D@A@B@C
[[2262 1274]
 [9738 5586]] 

D@A@C@B
[[1054 1107]
 [3966 4383]] 

D@B@A@C
[[2001  623]
 [6849 2247]] 

D@B@C@A
[[ 852 1670]
 [3888 7890]] 

D@C@A@B
[[3136 1722]
 [5964 3348]] 

D@C@B@A
[[1372 2940]
 [2778 6120]] 



In [29]:
#q2