In [219]:
#q3

In [267]:
import numpy as np

In [269]:
np.random.seed(0)
n_samples = 100

In [271]:
#自变量数据
x = np.random.uniform(0,4,n_samples) #范围内均匀分布随机数,范围左闭右开
#因变量数据
y = np.sin(0.4*np.pi*x) + 0.4 * np.random.randn(n_samples)

#此时x,y都是1D数组 这里为了保持原题,如果x生成完后立刻执行y如果后面的randn的生成没有reshape将会发生广播,生成100*100的矩阵

In [273]:
x = x.reshape(-1,1)
y = y.reshape(-1,1)

In [275]:
degree = 3
X_poly = np.ones_like(x)
for i in np.arange(degree)+1:
    #这里注意,column自动将1D看成2D列向量了
    X_poly = np.column_stack((X_poly,x**i))
X_poly

array([[1.00000000e+00, 2.19525402e+00, 4.81914019e+00, 1.05792369e+01],
       [1.00000000e+00, 2.86075747e+00, 8.18393328e+00, 2.34122482e+01],
       [1.00000000e+00, 2.41105350e+00, 5.81317900e+00, 1.40158856e+01],
       [1.00000000e+00, 2.17953273e+00, 4.75036293e+00, 1.03535715e+01],
       [1.00000000e+00, 1.69461920e+00, 2.87173422e+00, 4.86649595e+00],
       [1.00000000e+00, 2.58357645e+00, 6.67486728e+00, 1.72450299e+01],
       [1.00000000e+00, 1.75034885e+00, 3.06372108e+00, 5.36258065e+00],
       [1.00000000e+00, 3.56709200e+00, 1.27241454e+01, 4.53881972e+01],
       [1.00000000e+00, 3.85465104e+00, 1.48583347e+01, 5.72736952e+01],
       [1.00000000e+00, 1.53376608e+00, 2.35243837e+00, 3.60809017e+00],
       [1.00000000e+00, 3.16690015e+00, 1.00292566e+01, 3.17616542e+01],
       [1.00000000e+00, 2.11557968e+00, 4.47567738e+00, 9.46865211e+00],
       [1.00000000e+00, 2.27217824e+00, 5.16279397e+00, 1.17307881e+01],
       [1.00000000e+00, 3.70238655e+00, 1.37076662e

In [239]:
b = np.linalg.inv(X_poly.T @ X_poly) @ X_poly.T @ y #
b

array([[-0.2928996 ],
       [ 2.74802018],
       [-1.53682037],
       [ 0.20049216]])

In [241]:
y_hat = X_poly@b
y_hat

array([[ 0.45460397],
       [-0.31474351],
       [ 0.20898736],
       [ 0.47185572],
       [ 0.92630278],
       [ 0.00624191],
       [ 0.88386076],
       [-0.94520689],
       [-1.05190526],
       [ 1.03003911],
       [-0.63539723],
       [ 0.5408344 ],
       [ 0.36873617],
       [-1.00969382],
       [ 0.36845431],
       [ 0.48665129],
       [-0.08060292],
       [-0.78065067],
       [-0.58259418],
       [-0.89175097],
       [-1.05880727],
       [-0.663419  ],
       [ 0.80419537],
       [-0.59197478],
       [ 0.68443909],
       [ 0.03439871],
       [ 0.81534146],
       [-1.03510838],
       [ 0.57056785],
       [ 0.95200342],
       [ 1.13172227],
       [-0.56695031],
       [ 0.82267657],
       [ 0.36697489],
       [-0.09495682],
       [ 0.13934743],
       [ 0.16534348],
       [ 0.14264233],
       [-1.03407386],
       [-0.16212062],
       [ 1.07701051],
       [ 0.88561114],
       [-0.23507148],
       [ 0.28271922],
       [-0.09188949],
       [-0

In [243]:
epsilon = y - y_hat
epsilon

array([[-0.54700076],
       [ 0.23710243],
       [ 0.08881849],
       [-0.69443925],
       [ 0.5169298 ],
       [ 0.64728146],
       [ 0.39641032],
       [-0.10046386],
       [-0.36776102],
       [ 0.32883388],
       [-0.26921467],
       [ 0.41264974],
       [-0.00303171],
       [ 0.40213888],
       [ 0.12361921],
       [ 0.22007052],
       [ 0.18625682],
       [ 0.63077222],
       [-0.06266838],
       [ 0.10953586],
       [ 0.83335062],
       [-0.64349499],
       [-0.57991843],
       [ 0.27519335],
       [-0.59358381],
       [ 0.66811883],
       [-0.32097429],
       [-0.26322436],
       [ 0.69418411],
       [ 0.51122227],
       [ 0.58640235],
       [ 0.24763405],
       [-0.41672456],
       [ 0.67756742],
       [ 0.08206296],
       [ 0.21864471],
       [ 0.27837581],
       [-0.16411332],
       [ 0.28019874],
       [ 0.24926052],
       [ 0.04577346],
       [-0.51497384],
       [-0.0026612 ],
       [ 0.54595872],
       [-0.39434123],
       [-0

In [245]:
#GPT验证
import numpy as np
# 生成数据
np.random.seed(0)
n_samples = 100
x = np.random.uniform(0, 4, n_samples)
y = np.sin(0.4*np.pi * x) + 0.4*np.random.randn(n_samples)

# 设计矩阵 [1, x, x^2, x^3]
X = np.vander(x, 4, increasing=True)

# 最小二乘求系数 b
b = np.linalg.lstsq(X, y, rcond=None)[0]

# 预测和残差
y_hat = X @ b
eps = y - y_hat
b

array([-0.2928996 ,  2.74802018, -1.53682037,  0.20049216])

In [49]:
#q2

In [360]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures #
from sklearn.linear_model import LinearRegression

In [362]:
np.random.seed(0)
n_samples = 100
#自变量数据
x = np.random.uniform(0,4,n_samples) #范围内均匀分布随机数,范围左闭右开
#因变量数据
y = np.sin(0.4*np.pi*x) + 0.4 * np.random.randn(n_samples)

In [364]:
x = x.reshape(-1,1)
y = y.reshape(-1,1)

In [366]:
degree = 3
pf = PolynomialFeatures(degree = degree)
X_poly = pf.fit_transform(x) #
X_poly

array([[1.00000000e+00, 2.19525402e+00, 4.81914019e+00, 1.05792369e+01],
       [1.00000000e+00, 2.86075747e+00, 8.18393328e+00, 2.34122482e+01],
       [1.00000000e+00, 2.41105350e+00, 5.81317900e+00, 1.40158856e+01],
       [1.00000000e+00, 2.17953273e+00, 4.75036293e+00, 1.03535715e+01],
       [1.00000000e+00, 1.69461920e+00, 2.87173422e+00, 4.86649595e+00],
       [1.00000000e+00, 2.58357645e+00, 6.67486728e+00, 1.72450299e+01],
       [1.00000000e+00, 1.75034885e+00, 3.06372108e+00, 5.36258065e+00],
       [1.00000000e+00, 3.56709200e+00, 1.27241454e+01, 4.53881972e+01],
       [1.00000000e+00, 3.85465104e+00, 1.48583347e+01, 5.72736952e+01],
       [1.00000000e+00, 1.53376608e+00, 2.35243837e+00, 3.60809017e+00],
       [1.00000000e+00, 3.16690015e+00, 1.00292566e+01, 3.17616542e+01],
       [1.00000000e+00, 2.11557968e+00, 4.47567738e+00, 9.46865211e+00],
       [1.00000000e+00, 2.27217824e+00, 5.16279397e+00, 1.17307881e+01],
       [1.00000000e+00, 3.70238655e+00, 1.37076662e

In [368]:
lr = LinearRegression()
lr.fit(X_poly,y)

LinearRegression()

In [370]:
coef = lr.coef_[0]
intercept = lr.intercept_[0]
#注意array是可变类型
coef

array([ 0.        ,  2.74802018, -1.53682037,  0.20049216])

In [372]:
b = np.hstack((intercept,coef[1:]))
b

array([-0.2928996 ,  2.74802018, -1.53682037,  0.20049216])

In [374]:
y_hat = lr.predict(X_poly) #
y_hat

array([[ 0.45460397],
       [-0.31474351],
       [ 0.20898736],
       [ 0.47185572],
       [ 0.92630278],
       [ 0.00624191],
       [ 0.88386076],
       [-0.94520689],
       [-1.05190526],
       [ 1.03003911],
       [-0.63539723],
       [ 0.5408344 ],
       [ 0.36873617],
       [-1.00969382],
       [ 0.36845431],
       [ 0.48665129],
       [-0.08060292],
       [-0.78065067],
       [-0.58259418],
       [-0.89175097],
       [-1.05880727],
       [-0.663419  ],
       [ 0.80419537],
       [-0.59197478],
       [ 0.68443909],
       [ 0.03439871],
       [ 0.81534146],
       [-1.03510838],
       [ 0.57056785],
       [ 0.95200342],
       [ 1.13172227],
       [-0.56695031],
       [ 0.82267657],
       [ 0.36697489],
       [-0.09495682],
       [ 0.13934743],
       [ 0.16534348],
       [ 0.14264233],
       [-1.03407386],
       [-0.16212062],
       [ 1.07701051],
       [ 0.88561114],
       [-0.23507148],
       [ 0.28271922],
       [-0.09188949],
       [-0

In [378]:
espilon = y - y_hat
espilon

array([[-0.54700076],
       [ 0.23710243],
       [ 0.08881849],
       [-0.69443925],
       [ 0.5169298 ],
       [ 0.64728146],
       [ 0.39641032],
       [-0.10046386],
       [-0.36776102],
       [ 0.32883388],
       [-0.26921467],
       [ 0.41264974],
       [-0.00303171],
       [ 0.40213888],
       [ 0.12361921],
       [ 0.22007052],
       [ 0.18625682],
       [ 0.63077222],
       [-0.06266838],
       [ 0.10953586],
       [ 0.83335062],
       [-0.64349499],
       [-0.57991843],
       [ 0.27519335],
       [-0.59358381],
       [ 0.66811883],
       [-0.32097429],
       [-0.26322436],
       [ 0.69418411],
       [ 0.51122227],
       [ 0.58640235],
       [ 0.24763405],
       [-0.41672456],
       [ 0.67756742],
       [ 0.08206296],
       [ 0.21864471],
       [ 0.27837581],
       [-0.16411332],
       [ 0.28019874],
       [ 0.24926052],
       [ 0.04577346],
       [-0.51497384],
       [-0.0026612 ],
       [ 0.54595872],
       [-0.39434123],
       [-0