In [4]:
import numpy as np

In [6]:
#Q1

In [11]:
A = np.array([[1,0],
              [0,2]])
lambdas,V = np.linalg.eig(A)
print(lambdas)
print(V)

[1. 2.]
[[1. 0.]
 [0. 1.]]


In [13]:
A = np.array([[-1,0],
              [0,-2]])
lambdas,V = np.linalg.eig(A)
print(lambdas)
print(V)

[-1. -2.]
[[1. 0.]
 [0. 1.]]


In [15]:
A = np.array([[1,-1],
              [-1,1]])
lambdas,V = np.linalg.eig(A)
print(lambdas)
print(V)

[2. 0.]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [17]:
A = np.array([[-1,1],
              [1,-1]])
lambdas,V = np.linalg.eig(A)
print(lambdas)
print(V)

[ 0. -2.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [19]:
#Q3

In [21]:
A = np.array([[0,1,1],
              [1,0,1],
              [1,1,0]])
lambdas,V = np.linalg.eig(A)
print(lambdas)
print(V)

[-1.  2. -1.]
[[-0.81649658  0.57735027 -0.27880153]
 [ 0.40824829  0.57735027 -0.5252061 ]
 [ 0.40824829  0.57735027  0.80400763]]


In [25]:
A = np.array([[0,1,1],
              [1,1,0],
              [1,0,1]])
lambdas,V = np.linalg.eig(A)
print(lambdas)
print(V)

[-1.  2.  1.]
[[-8.16496581e-01  5.77350269e-01 -1.57009246e-16]
 [ 4.08248290e-01  5.77350269e-01 -7.07106781e-01]
 [ 4.08248290e-01  5.77350269e-01  7.07106781e-01]]


In [27]:
A = np.array([[0,1,0],
              [1,0,1],
              [0,1,0]])
lambdas,V = np.linalg.eig(A)
print(lambdas)
print(V)

[-1.41421356e+00 -2.78621481e-17  1.41421356e+00]
[[ 5.00000000e-01  7.07106781e-01  5.00000000e-01]
 [-7.07106781e-01 -6.42652527e-17  7.07106781e-01]
 [ 5.00000000e-01 -7.07106781e-01  5.00000000e-01]]


In [35]:
A = np.array([[1,0,0],
              [0,2,0],
              [0,0,3]])
lambdas,V = np.linalg.eig(A)
print(lambdas)
print(V)

[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
A = np.array([[-1,0,0],
              [0,-2,0],
              [0,0,-3]])
lambdas,V = np.linalg.eig(A)
print(lambdas)
print(V)

[-1. -2. -3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
A = np.array([[1,0,0],
              [0,0,0],
              [0,0,3]])
lambdas,V = np.linalg.eig(A)
print(lambdas)
print(V)

[1. 0. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
A = np.array([[-1,0,0],
              [0,0,0],
              [0,0,-3]])
lambdas,V = np.linalg.eig(A)
print(lambdas)
print(V)

[-1.  0. -3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
A = np.array([[0,1,0],
              [1,0,0],
              [0,0,0]])
lambdas,V = np.linalg.eig(A)
print(lambdas)
print(V)

[ 1. -1.  0.]
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [45]:
A = np.array([[0,0,1],
              [0,0,1],
              [1,1,0]])
lambdas,V = np.linalg.eig(A)
print(lambdas)
print(V)

[-1.41421356e+00 -2.78621481e-17  1.41421356e+00]
[[ 5.00000000e-01 -7.07106781e-01 -5.00000000e-01]
 [ 5.00000000e-01  7.07106781e-01 -5.00000000e-01]
 [-7.07106781e-01  6.42652527e-17 -7.07106781e-01]]


In [47]:
A = np.array([[1,0,0],
              [0,1,0],
              [0,0,-1]])
lambdas,V = np.linalg.eig(A)
print(lambdas)
print(V)

[ 1.  1. -1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
A = np.array([[-1,0,0],
              [0,1,0],
              [0,0,-1]])
lambdas,V = np.linalg.eig(A)
print(lambdas)
print(V)

[-1.  1. -1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
