In [1]:
#q1

In [3]:
import numpy as np

In [13]:
q1_arr = np.eye(3)

In [19]:
q1_a = q1_arr[:,0]
q1_b = q1_arr[:,1]
q1_c = q1_arr[:,2]

In [21]:
np.dot(q1_a,q1_b)

0.0

In [23]:
np.dot(q1_a,q1_c)

0.0

In [25]:
np.dot(q1_b,q1_c)

0.0

In [27]:
#q2

In [37]:
q2_arr1 = np.random.randint(1,10,(5,5))
q2_arr1

array([[8, 7, 7, 3, 4],
       [9, 7, 8, 1, 4],
       [3, 4, 6, 8, 4],
       [2, 2, 6, 7, 3],
       [4, 8, 3, 6, 6]])

In [39]:
q2_arr2 = np.random.randint(1,10,(5,10))
q2_arr2

array([[9, 7, 4, 6, 8, 7, 4, 9, 5, 4],
       [9, 2, 9, 1, 8, 2, 7, 2, 3, 1],
       [4, 9, 4, 3, 7, 2, 3, 1, 4, 9],
       [4, 7, 3, 7, 1, 6, 7, 9, 6, 2],
       [6, 8, 4, 2, 1, 5, 3, 3, 2, 1]])

In [43]:
q2_arr3 = np.random.randint(1,10,(10,5))
q2_arr3

array([[8, 4, 4, 3, 8],
       [4, 7, 2, 3, 9],
       [5, 9, 8, 4, 6],
       [7, 1, 7, 4, 3],
       [6, 3, 5, 5, 9],
       [3, 3, 4, 2, 1],
       [3, 5, 3, 7, 2],
       [6, 2, 2, 1, 4],
       [9, 3, 5, 4, 1],
       [9, 8, 3, 4, 2]])

In [94]:
def diagonal(array):
    q2_diag_1d = np.array([])
    if array.shape[0] >= array.shape[1]:
        for i in np.arange(0,array.shape[1]):
            q2_diag_1d = np.append(q2_diag_1d,array[i,i])
        print(q2_diag_1d)

    elif array.shape[0] < array.shape[1]:
        for i in np.arange(0,array.shape[0]):
            q2_diag_1d = np.append(q2_diag_1d,array[i,i])  
        print(q2_diag_1d)

    return q2_diag_1d


In [96]:
diagonal(q2_arr1)

[8. 7. 6. 7. 6.]


array([8., 7., 6., 7., 6.])

In [98]:
diagonal(q2_arr2)

[9. 2. 4. 7. 1.]


array([9., 2., 4., 7., 1.])

In [100]:
diagonal(q2_arr3)

[8. 7. 8. 4. 9.]


array([8., 7., 8., 4., 9.])

In [102]:
#q3

In [130]:
q3_arr1 = diagonal(q2_arr1)
q3_arr2 = diagonal(q2_arr2)
q3_arr3 = diagonal(q2_arr3)

[8. 7. 6. 7. 6.]
[9. 2. 4. 7. 1.]
[8. 7. 8. 4. 9.]


(5,)

In [136]:
def build_diagonal(array_1d):
    #shape返回一维数组,需要按照位置提取
    shape = array_1d.shape[0]
    zero_arr = np.zeros((shape,shape))
    for i in np.arange(0,shape):
        zero_arr[i,i] = array_1d[i]
        q3_diag_2d = zero_arr
    print(q3_diag_2d)
    return(q3_diag_2d)

In [138]:
build_diagonal(q3_arr1)

[[8. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0.]
 [0. 0. 6. 0. 0.]
 [0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 6.]]


array([[8., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0.],
       [0., 0., 6., 0., 0.],
       [0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 6.]])

In [140]:
build_diagonal(q3_arr2)

[[9. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 1.]]


array([[9., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 1.]])

In [142]:
build_diagonal(q3_arr3)

[[8. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0.]
 [0. 0. 8. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 9.]]


array([[8., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 9.]])

In [144]:
#q4

In [148]:
np.triu(q2_arr1)

array([[8, 7, 7, 3, 4],
       [0, 7, 8, 1, 4],
       [0, 0, 6, 8, 4],
       [0, 0, 0, 7, 3],
       [0, 0, 0, 0, 6]])

In [152]:
#q5

In [154]:
np.tril(q2_arr1)

array([[8, 0, 0, 0, 0],
       [9, 7, 0, 0, 0],
       [3, 4, 6, 0, 0],
       [2, 2, 6, 7, 0],
       [4, 8, 3, 6, 6]])

In [156]:
#q6  判断转置矩阵与原矩阵相比 是否为对称矩阵

In [160]:
q6_arr = np.random.randint(0,10,(5,5))
q6_arr

array([[9, 7, 9, 3, 3],
       [7, 6, 7, 9, 1],
       [4, 1, 9, 8, 0],
       [0, 8, 4, 7, 4],
       [1, 3, 2, 0, 7]])

In [162]:
q6_arr_T = q6_arr.T
q6_arr_T

array([[9, 7, 4, 0, 1],
       [7, 6, 1, 8, 3],
       [9, 7, 9, 4, 2],
       [3, 9, 8, 7, 0],
       [3, 1, 0, 4, 7]])

In [166]:
np.array_equal(q6_arr,q6_arr_T)

False

In [172]:
q6_arr_2 = np.array([[1,2,3],
                     [2,3,4],
                     [3,4,5]])

In [174]:
q6_arr_2_T = q6_arr_2.T

In [176]:
np.array_equal(q6_arr_2,q6_arr_2_T)

True

In [178]:
#q7

In [186]:
q7 = np.random.randint(0,10,(5,12))
q7

array([[4, 6, 5, 2, 6, 3, 3, 5, 0, 0, 8, 1],
       [6, 7, 1, 7, 5, 7, 2, 4, 8, 9, 5, 8],
       [5, 8, 4, 3, 6, 7, 5, 2, 2, 7, 4, 0],
       [0, 8, 3, 9, 5, 2, 3, 2, 0, 5, 3, 3],
       [1, 5, 4, 6, 4, 9, 5, 8, 4, 8, 0, 0]])

In [198]:
q7_1_1 = q7[0:3,:]  #:中左闭右开,为了算法的简洁
q7_1_1

array([[4, 6, 5, 2, 6, 3, 3, 5, 0, 0, 8, 1],
       [6, 7, 1, 7, 5, 7, 2, 4, 8, 9, 5, 8],
       [5, 8, 4, 3, 6, 7, 5, 2, 2, 7, 4, 0]])

In [200]:
q7[3:5,:]

array([[0, 8, 3, 9, 5, 2, 3, 2, 0, 5, 3, 3],
       [1, 5, 4, 6, 4, 9, 5, 8, 4, 8, 0, 0]])

In [202]:
q7[:,0:5]

array([[4, 6, 5, 2, 6],
       [6, 7, 1, 7, 5],
       [5, 8, 4, 3, 6],
       [0, 8, 3, 9, 5],
       [1, 5, 4, 6, 4]])

In [210]:
q7[:,5:12]

array([[3, 3, 5, 0, 0, 8, 1],
       [7, 2, 4, 8, 9, 5, 8],
       [7, 5, 2, 2, 7, 4, 0],
       [2, 3, 2, 0, 5, 3, 3],
       [9, 5, 8, 4, 8, 0, 0]])

In [212]:
q7[0:3,0:5]

array([[4, 6, 5, 2, 6],
       [6, 7, 1, 7, 5],
       [5, 8, 4, 3, 6]])

In [214]:
q7[0:3,5:12]

array([[3, 3, 5, 0, 0, 8, 1],
       [7, 2, 4, 8, 9, 5, 8],
       [7, 5, 2, 2, 7, 4, 0]])

In [218]:
q7[3:5,0:5]

array([[0, 8, 3, 9, 5],
       [1, 5, 4, 6, 4]])

In [220]:
q7[3:5,5:12]

array([[2, 3, 2, 0, 5, 3, 3],
       [9, 5, 8, 4, 8, 0, 0]])