In [1]:
import numpy as np

In [21]:
A = np.array([[0,-1],
              [-1,-1],
              [-1,0]])

In [23]:
G_2 = A@A.T

In [7]:
G_2

array([[1, 1, 0],
       [1, 2, 1],
       [0, 1, 1]])

In [25]:
lambdas,U = np.linalg.eigh(G_2)
lambdas,U

(array([2.56090598e-16, 1.00000000e+00, 3.00000000e+00]),
 array([[-5.77350269e-01,  7.07106781e-01,  4.08248290e-01],
        [ 5.77350269e-01,  9.13969213e-18,  8.16496581e-01],
        [-5.77350269e-01, -7.07106781e-01,  4.08248290e-01]]))

In [27]:
U,S,V = np.linalg.svd(A)
U,S,V

(array([[ 4.08248290e-01, -7.07106781e-01,  5.77350269e-01],
        [ 8.16496581e-01, -2.18777420e-16, -5.77350269e-01],
        [ 4.08248290e-01,  7.07106781e-01,  5.77350269e-01]]),
 array([1.73205081, 1.        ]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

In [29]:
np.sqrt(4)

2.0

In [31]:
A = np.array([[5/4,-3/4],
              [-3/4,5/4]])

In [33]:
U,S,V = np.linalg.svd(A)
U,S,V

(array([[-0.70710678,  0.70710678],
        [ 0.70710678,  0.70710678]]),
 array([2. , 0.5]),
 array([[-0.70710678,  0.70710678],
        [ 0.70710678,  0.70710678]]))

In [68]:
A = np.array([[0,1,1],
              [1,0,1],
              [1,1,0]])

In [70]:
G_1 = A.T@A

In [72]:
lambdas_G_1,V_1 = np.linalg.eigh(G_1)
lambdas_G_1,V_1

(array([1., 1., 4.]),
 array([[ 0.57307506, -0.58159406,  0.57735027],
        [-0.79021276, -0.20550053,  0.57735027],
        [ 0.2171377 ,  0.78709459,  0.57735027]]))

In [74]:
G_2 = A@A.T

In [76]:
lambdas_G_2,U_1 = np.linalg.eigh(G_2)
lambdas_G_2,U_1

(array([1., 1., 4.]),
 array([[ 0.57307506, -0.58159406,  0.57735027],
        [-0.79021276, -0.20550053,  0.57735027],
        [ 0.2171377 ,  0.78709459,  0.57735027]]))

In [66]:
U,S,V = np.linalg.svd(A)
U,S,V

(array([[-5.77350269e-01, -1.00875766e-16,  8.16496581e-01],
        [-5.77350269e-01, -7.07106781e-01, -4.08248290e-01],
        [-5.77350269e-01,  7.07106781e-01, -4.08248290e-01]]),
 array([2., 1., 1.]),
 array([[-0.57735027, -0.57735027, -0.57735027],
        [-0.        ,  0.70710678, -0.70710678],
        [-0.81649658,  0.40824829,  0.40824829]]))

In [80]:
V_1.T@V_1

array([[ 1.00000000e+00,  1.92543785e-16,  2.81644282e-16],
       [ 1.92543785e-16,  1.00000000e+00, -1.09365997e-16],
       [ 2.81644282e-16, -1.09365997e-16,  1.00000000e+00]])

In [82]:
V.T @ V

array([[ 1.00000000e+00, -9.72785220e-18, -9.72785220e-18],
       [-9.72785220e-18,  1.00000000e+00, -9.36825298e-17],
       [-9.72785220e-18, -9.36825298e-17,  1.00000000e+00]])

In [85]:
A = np.array([[0,1,1],
              [1,1,0]])

In [87]:
G_1 = A.T @ A

In [89]:
G_2 = A @ A.T

In [95]:
lambdas_G_1,V_1 = np.linalg.eigh(G_1)

In [97]:
lambdas_G_2,V_2 = np.linalg.eigh(G_2)

In [101]:
lambdas_G_1,V_1

(array([2.56090598e-16, 1.00000000e+00, 3.00000000e+00]),
 array([[-5.77350269e-01,  7.07106781e-01,  4.08248290e-01],
        [ 5.77350269e-01,  9.13969213e-18,  8.16496581e-01],
        [-5.77350269e-01, -7.07106781e-01,  4.08248290e-01]]))

In [103]:
lambdas_G_2,V_2

(array([1., 3.]),
 array([[-0.70710678,  0.70710678],
        [ 0.70710678,  0.70710678]]))

In [105]:
U,S,V = np.linalg.svd(A)
U,S,V

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([1.73205081, 1.        ]),
 array([[-4.08248290e-01, -8.16496581e-01, -4.08248290e-01],
        [ 7.07106781e-01,  1.65204549e-16, -7.07106781e-01],
        [ 5.77350269e-01, -5.77350269e-01,  5.77350269e-01]]))