In [1]:
import numpy as np

In [3]:
#q1

In [5]:
A = np.array([[1,1],
              [0,1]])

In [10]:
lambdas,V = np.linalg.eig(A)

In [13]:
lambdas #代数重数为2 集合重数为1

array([1., 1.])

In [15]:
V#不可对角化,两列线性相关

array([[ 1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  2.22044605e-16]])

In [17]:
A = np.array([[2,0],
              [0,2]])
lambdas,V = np.linalg.eig(A)

In [21]:
lambdas

array([2., 2.])

In [23]:
V#任何向量都可行,这里是numpy给出的一组基 V的列向量永远是向量基
#化简出现0=0 表示约束全没了,连次方都不知道,理论上有无数个所以整个R^2都是特征子空间
#写成两个是为了匹配A的矩阵乘法,就是AV = VD 也就是对角化的前身
#这里实在是有太多符合的向量,随便抽出两个线性无关的就可以组成对角化

array([[1., 0.],
       [0., 1.]])

In [26]:
A = np.array([[1/2,0],
              [0,2]])
lambdas,V = np.linalg.eig(A)

In [28]:
lambdas

array([0.5, 2. ])

In [30]:
V#lambdas的顺序一定与V的列向量顺序对应
#所以公式中AV = lambdas @ V 这里A可以不变,但是V列向量顺序一定要和lambda对应,编程中就是V和λ的索引

array([[1., 0.],
       [0., 1.]])

In [33]:
A = np.array([[1,0],
              [1,1]])
lambdas,V = np.linalg.eig(A)

In [35]:
lambdas

array([1., 1.])

In [37]:
V

array([[ 0.00000000e+00,  2.22044605e-16],
       [ 1.00000000e+00, -1.00000000e+00]])

In [40]:
A = np.array([[0,1],
              [1,0]])
lambdas,V = np.linalg.eig(A)

In [42]:
lambdas

array([ 1., -1.])

In [44]:
V

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [47]:
A = np.array([[1/2,1/2],
              [1/2,1/2]])
lambdas,V = np.linalg.eig(A)

In [49]:
lambdas

array([1.00000000e+00, 1.11022302e-16])

In [51]:
V#第二列是λ为0的特征子空间
#λ为0的特征向量是是零空间的非零向量,这个也满足等式,那个定义.

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])